mysensors/MySensors

libraries/MySensors/MySensor.cpp

I had a repeater stuck at 255 in nc.distance because the gateway went down for a short time and miss the I_FIND_PARENT message when got back.

fix a case where parent distance from repeater get stuck at 255

---

libraries/MySensors/MySensor.cpp

perhaps the documentation I wrote should be improved?

Fetch id through repeaters

---

libraries/MySensors/MyMessage.cpp
libraries/MySensors/MyMessage.h

I was thinking in the possibility of sending a C_SET message with a P_CUSTOM payload.

get custom string from msg that isn't a stream type

---

libraries/MySensors/MySensor.cpp
libraries/MySensors/MySensor.h

Adds a wait helper, useful for repeaters and sensors that read from the network.

Add wait() helper that doesn't sleep. 

---

libraries/MySensors/MySensor.h

fix convBuf size to print P_CUSTOM payloads

---

libraries/MySensors/MySensor.cpp

Simplify wait(), added watchdog reset to wait() and waitForReply().
Substituted all waitForReply() for wait(2000) to reduce code
size/complexity

simplify wait(), substitute waitForReply(), adding watchdog resets

---

libraries/MySensors/MyGateway.cpp

To prevent incomplete or chunked data being sent by the gateway

check for invalid input on gateway

---

libraries/sha204/examples/sha204_personalizer/sha204_personalizer.ino

New default pin is A3.
New option to skip UART confirmation: SKIP_UART_CONFIRMATION
This option prohibits the possibility to auto-generate key as there
will probably not be a way to show the generated key to the user.
More copy+paste friendly serial output of the generated key for
insertion into personalization sketch.

ATSHA204 personalization sketch updated

---

libraries/MySensors/MyConfig.h
libraries/MySensors/MyRFDriverNRF24.h
libraries/MySensors/examples/EthernetGateway/EthernetGateway.ino
libraries/MySensors/examples/MQTTGateway/MQTTGateway.ino

For the future parser function.

add MYSENSORS_MQTT_GATEWAY definition

---

libraries/MySensors/MyGateway.cpp

Revert "check for invalid input on gateway"

---

libraries/MySensors/examples/MQTTGateway/MQTTGateway.ino

There is probably a better solution, this was the simplest I came up with.
Changed some variables types from uint8_t to byte to make simple for common arduino user.

fix multiple mqtt clients with openhab

---

libraries/MySensors/MySensor.cpp

Various fixes and tweaks to permit a gateway to request
signatures from nodes.
The following messages will not be signed (nor verified):
* All signing-related handshake messages
* All ID-related handshake messages
* All ACKs

Support for gateways to request signed messages

---

libraries/MySensors/examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino

Modified watermeter pulse example
- Current master code would send unlimited gateway get VAR_1 requests at the fasted interval possible
- New code start counting pulses, when received the VAR_1, it will be added. No missing pulses
- Cleaned up the code, corrected some spelling/comments

Modified WaterMeterPulseSensor Example

---

libraries/MySensors/MySensor.cpp

adding back time handler

---

libraries/MySensors/examples/MysensorMicro/MysensorMicro.ino

Changed the name it reports to controler, from EnvironmentSensor to MysensorMicro
changed delay() in test routine to use Serial.flush() to flush serial during testing.

updates to mysensorMicro sketch

---

hardware/MySensors/avr/boards.txt
hardware/MySensors/avr/platform.txt
hardware/MySensors/avr/variants/micro/pins_arduino.h

Added hardware folder for mysensors specific arduino boards

Mysensor HW definitions for mysensors micro board

---

libraries/MySensors/examples/MysensorMicro/MysensorMicro.ino

mysensorsmicro sketch updated, with input from Bruce.

Updated with input from Bruce Lacey

---

hardware/MySensors/avr/boards.txt
hardware/MySensors/avr/platform.txt

Renamed board to Sensebender Micro
and corrected a couple of warnings caused by wrong paths in platform.txt

Corrected board definitons

---

hardware/MySensors/avr/boards.txt

Updated boards.txt, so we are able to choose different clock frequencies for mysensors Micro (user has to switch to the right frequency in the sketch, as we are running 8Mhz due to bootloader baudrate).

Boards.txt updated

---

libraries/MySensors/examples/SensebenderMicro/SensebenderMicro.ino
libraries/RunningAverage/RunningAverage.cpp
libraries/RunningAverage/RunningAverage.h
libraries/RunningAverage/examples/fillValue/fillValue.ino
libraries/RunningAverage/examples/ra_MinMaxTest/ra_MinMaxTest.ino
libraries/RunningAverage/examples/ra_hour/ra_hour.ino
libraries/RunningAverage/examples/ra_test/ra_test.ino
libraries/RunningAverage/keywords.txt

Same as in #111 but with the following corrections:
switching to 1Mhz after 5 measurements have been taken
initializes the serialport at 115200 baud.

Here we go again

---

libraries/MySensors/examples/IrrigationController/IrrigationController.ino

Jim's (BulldogLowell) irrigation controller code.

Irrigation Controller

---

libraries/MySensors/examples/IrrigationController/IrrigationController.ino

Additional library is no longer needed.  Updated comments in code

Updated Comments

---

libraries/MySensors/examples/SensebenderMicro/SensebenderMicro.ino

I have implemented thresholds on temperature / humidity measurements, so it only transmits if changes are above 0.5 degrees (absolute with reference to last transmitted value) or 0.5 on a moving average on the last two measurements done on humidity

Updated sensebender Micro sketch, for better transmition handling

---

libraries/MySensors/examples/SensebenderMicro/SensebenderMicro.ino

for the code that determines if it should transmit

Corrected a celcius/fahrenheit conversion, 

---

libraries/MySensors/examples/SensebenderMicro/SensebenderMicro.ino

as it made one of my sensors go haywire, so decided to remove that part from the generic sensebender micro code, in order to not make trouble for others

Removed "sensor conditioning code" 

---

libraries/MySensors/examples/LightningSensor/LightningSensor.ino
libraries/PWF_AS3935_Lightning_Sensor/PWF_Lightning_Sensor.txt
libraries/PWF_AS3935_Lightning_Sensor/PWFusion_AS3935.cpp
libraries/PWF_AS3935_Lightning_Sensor/PWFusion_AS3935.h

This is an example sketch for the Playing With Fusion Lightning Sensor breakout board and the required library

Example sketch for PWF Lightning Sensor

---

libraries/MySensors/MySensor.cpp
libraries/MySensors/utility/SPIFlash.cpp
libraries/MySensors/utility/SPIFlash.h

- OTA updates (fix, beta)
- update flash driver (now page-boundary safe)

Sensebender OTA

---

libraries/MySensors/MySensor.cpp

- add OTA-ongoing check
- reduce OTA code size

OTA improvements

---

libraries/MySensors/examples/SensebenderBlink/SensebenderBlink.ino

Simple sketch to test OTA updates with MYSController

Sensebender OTA: Blink

---

libraries/MySensors/MyMessage.h
libraries/MySensors/examples/MockMySensors/MockMySensors.ino
libraries/MySensors/examples/MockMySensors/README.md

MyMessage.h: Added some comments and presentation types from the web site, fixed a small typo
MockMySensors sketch: Fixed some small issues to conform to the 1.5 API (S_HEATER still needs to be done)

MyMessage.h / MockMySensors changes

---

libraries/MySensors/MySensor.cpp
libraries/MySensors/examples/MockMySensors/MockMySensors.ino
libraries/MySensors/examples/MockMySensors/README.md

Name changes

---

libraries/MySensors/examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino

Always send volume when not in sleep mode
send frequency set to 30 seconds
i was receiving interrupts even if i did not connected the pins.
With this patch, it working perfect!
When not in sleep mode, the counter value is now transmitted every 30 seconds, regardless if there is a change.
This way, there will be no timeout

initialize digital pins internal pullup resistor

---

libraries/MySensors/examples/MQTTClientGateway/MQTTClientGateway.ino
libraries/MySensors/examples/MQTTClientGateway/MyMQTTClient.h
libraries/PubSubClient/CHANGES.txt
libraries/PubSubClient/LICENSE.txt
libraries/PubSubClient/PubSubClient.cpp
libraries/PubSubClient/PubSubClient.h
libraries/PubSubClient/examples/mqtt_auth/mqtt_auth.ino
libraries/PubSubClient/examples/mqtt_basic/mqtt_basic.ino
libraries/PubSubClient/examples/mqtt_publish_in_callback/mqtt_publish_in_callback.ino
libraries/PubSubClient/examples/mqtt_stream/mqtt_stream.ino
libraries/PubSubClient/keywords.txt

MQTTClientGateway acting as a client to the MQTT broker Mosquito.
I agree to the CLA of MySensors.

Add MQTTClientGateway

---

libraries/MySensors/examples/MockMySensors/MockMySensors.ino

Added V_STATUS to S_HEATER, as this is also supported
Added S_MOISTURE (a moisture sensor)

Added V_STATUS to S_HEATER, and S_MOISTURE

---

libraries/MySensors/core/MyMessage.cpp
libraries/MySensors/core/MyMessage.h

Fixes data type length problem when messages travels between 8/16/32 bit
architectures. 
close #223

Use sdtint for in MyMessage.

---

libraries/MySensors/core/MySensorCore.cpp

wait() issue

---

libraries/MySensors/core/MyGatewayTransportMQTTClient.cpp

http://forum.mysensors.org/topic/1870/esp8266-wifi-gateway-port-for-mysensors/138

Fix problem MQTT gateway problem reported by @FotoFieber

---

libraries/MySensors/MySensor.h
libraries/MySensors/core/MyTransport.cpp

http://forum.mysensors.org/topic/1021/security-introducing-signing-support-to-mysensors/176

Fix MY_SIGNING_REQUEST_SIGNATURES compile error

---

libraries/MySensors/core/MyTransport.cpp

Nonce-state machine got locked in SIGN_OK state.

Fixed bug in nonce exchange

---

libraries/MySensors/examples/GatewayESP8266/GatewayESP8266.ino

This is just a minor nitpick, but might save someone some troubleshooting.

GatewayESP8266: Add GND to list of pins to connect

---

libraries/MySensors/MyConfig.h
libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MyTransportRFM69.cpp
libraries/MySensors/drivers/RFM69/RFM69.cpp
libraries/MySensors/examples/GatewayESP8266/GatewayESP8266.ino

Correct problem with define HW-variant
Clean up GatewayESP8266 comments
Change the debug message at startup (include version)

Detect if initialization fails for RFM69 radio

---

libraries/MySensors/core/MyGatewayTransport.cpp
libraries/MySensors/core/MyGatewayTransportEthernet.cpp

Reduce memory footprint form W5100 gateway

Handle internal messages sent from controller to gateway

---

libraries/MySensors/core/MyTransport.cpp

For repeated messages, sign flag must not be touched.

Fixed bug in repeaters when forwarding signed messages

---

libraries/MySensors/MyConfig.h
libraries/MySensors/MySensor.h
libraries/MySensors/core/MyCapabilities.h
libraries/MySensors/core/MyGatewayTransportMQTTClient.cpp
libraries/MySensors/core/MyMainDefault.cpp
libraries/MySensors/core/MyMainESP8266.cpp
libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/examples/RFIDLockSensor/RFIDLockSensor.ino
libraries/MySensors/examples/RelayActuator/RelayActuator.ino

Call sketch setup() before presentation()
Bugfix in RFIDLockSensor
Disable remote reset option
Topic comparison bugix MQTT gateway

Capabilities embryo, misc fixes

---

libraries/MySensors/examples/ClearEepromConfig/ClearEepromConfig.ino

ClearEepromConfig: Fix spelling mistake

---

libraries/MySensors/core/MyGatewayTransportMQTTClient.cpp

@henrikekblad I have added fix as your guidance. I'm not familiar with C++. Kindly correct it if I have added anything wrongly.
- This fix will support to send `C_STREAM` to MySensors world.
- I have tested with master branch of [MyController.org](http://www.mycontroller.org) controller, it works perfectly.

Fix to send C_STREAM to MySensors network world

---

libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySigningAtsha204Soft.cpp

Improve pseudo-RNG quality: move randomseed() and include 255 in random()

20151211_RNG

---

libraries/MySensors/core/MyMessage.h
libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MyTransport.cpp

response to I_HEARTBEAT request is I_HEARTBEAT_RESPONSE with incremental counter

I_HEARTBEAT_RESPONSE and typo

---

libraries/MySensors/core/MySensorCore.cpp

Change the way the heartbeat counter works: Heartbeat counter is incremented with every message sent. This value can also be used to estimate the node's uptime.

Heartbeat enhancement

---

libraries/MySensors/core/MyTransport.cpp
libraries/MySensors/examples/SecureActuator/SecureActuator.ino

I have not the opportunity to verify these at the moment. If someone has that possibility within the next few days, I would highly appreciate some help (ping @tekka007 ;) ).

Resolve open bugs relating to security

---

hardware/MySensors/samd/platform.txt
libraries/MySensors/core/MyHwSAMD.h
libraries/MySensors/library.properties

Fixes compile error / Warnings on samd arch

snprintf_P missing in arduino core for samd, so have a local macro

---

libraries/MySensors/library.json

* This library in Web Registry: http://platformio.org/#!/lib/show/548/MySensors
* Specification: [library.json](http://docs.platformio.org/en/latest/librarymanager/config.html)
* Library Manager:  http://docs.platformio.org/en/latest/librarymanager/index.html

@PlatformIO Library Registry manifest file

---

libraries/MySensors/core/MyTransport.cpp

Clearing payload buffer at the end of the message.
Test run with SecureActuator and DimmableLEDActuator.

Fix null termination issue

---

libraries/MySensors/examples/OregonSensorDecode/OregonSensorDecode.ino
libraries/Oregon/INSTALL.txt
libraries/Oregon/LICENSE.md
libraries/Oregon/README.md
libraries/Oregon/examples/MySensors_example/MySensors_example.ino
libraries/Oregon/examples/simple_example/simple_example.ino
libraries/Oregon/keywords.txt
libraries/Oregon/library.json
libraries/Oregon/library.properties
libraries/Oregon/src/Oregon.h

Hi,
I like to add my new Oregon library 1.0.0.
the explanations here: http://forum.mysensors.org/topic/2655/arduino-library-for-oregon-sensors-433mhz
Thanks in advance

Add Oregon decoder library

---

libraries/Adafruit_FONA_Library/.travis.yml
libraries/Adafruit_FONA_Library/Adafruit_FONA.cpp
libraries/Adafruit_FONA_Library/Adafruit_FONA.h
libraries/Adafruit_FONA_Library/README.md
libraries/Adafruit_FONA_Library/examples/FONA3G_setbaud/FONA3G_setbaud.ino
libraries/Adafruit_FONA_Library/examples/FONA_SMS_Response/FONA_SMS_Response.ino
libraries/Adafruit_FONA_Library/examples/FONAtest/FONAtest.ino
libraries/Adafruit_FONA_Library/examples/GPS/GPS.ino
libraries/Adafruit_FONA_Library/examples/IncomingCall/IncomingCall.ino
libraries/Adafruit_FONA_Library/library.properties
libraries/MySensors/examples/SMSGatewayNode/SMSGatewayNode.ino

Adding SMS Gateway node example and supporting library (Adafruit FONA).

Adding SMS Gateway node example and supporting library.

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp
libraries/MySensors/examples/GatewayW5100/GatewayW5100.ino

Using 
#define MY_USE_UDP 
Failied building on AVR (only worked on ESP)
Fixes https://github.com/mysensors/Arduino/issues/369

Fix compile problems when enabling UDP

---

libraries/MySensors/core/MyGatewayTransportMQTTClient.cpp

Fixes: https://github.com/mysensors/Arduino/issues/366

Turn off access point when running ESP8266 MQTT client

---

libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/examples/RelayActuator/RelayActuator.ino
libraries/MySensors/keywords.txt

Add before() for initialisations before radio hogs SPI

---

libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/core/MyTransport.cpp

conditionalWait() loops until time passed or specified command received. 
=> speed up booting

Implementation conditionalWait()

---

libraries/MySensors/examples/GatewayESP8266OTA/GatewayESP8266OTA.ino

(as separate sketch)
read here for additional info: https://github.com/esp8266/Arduino/blob/master/doc/ota_updates/readme.md

Add OTA FW update support for ESP8266

---

libraries/MySensors/core/MyMessage.h

S_RGB does not exist. Changing to S_RGB_LIGHT and S_RGBW_LIGHT

S_RGB does not exist. Changing to S_RGB_LIGHT and S_RGBW_LIGHT

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp

values get the rest of value from reading before / Integer and Float affected #322
just with UDP...

When receiving a number of messages, string might include old Data

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp

Fixing https://github.com/mysensors/Arduino/issues/405

Do not close TCP connection after each send.

---

libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/core/MyTransport.cpp

- re-assign ID via I_ID_RESPONSE <newID>
- implement getParentNodeID(), fixes #423

re-assign node ID

---

libraries/MySensors/drivers/RFM69/RFM69.cpp
libraries/MySensors/drivers/RFM69/RFM69.h
libraries/MySensors/drivers/RFM69/RFM69registers.h

- fixes #436
- fixes #410
- fixes #407

update RFM69 driver

---

libraries/MySensors/core/MySigning.cpp
libraries/MySensors/core/MySigning.h
libraries/MySensors/core/MySigningAtsha204.cpp
libraries/MySensors/core/MySigningAtsha204Soft.cpp

Add and use timing neutral memcmp for signing

---

libraries/MySensors/core/MyHwATMega328.cpp

Add volatile qualifier to pinIntTrigger declaration

---

libraries/MySensors/core/MyHwATMega328.cpp
libraries/MySensors/core/MyHwESP8266.cpp
libraries/MySensors/core/MyHwSAMD.cpp

Split #439 / Part 1
- Harmonize HWabstraction functions
- Add hwFreeMem()

Add hwFreeMem() function

---

libraries/MySensors/MySensor.h
libraries/MySensors/core/MyOTAFirmwareUpdate.cpp
libraries/MySensors/core/MyOTAFirmwareUpdate.h
libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/core/MyTransport.cpp
libraries/MySensors/core/MyTransport.h

Split #439 / Part 3
- Move OTA FW update code to MyOTAFirmwareUpdate

Refactor OTA update code

---

libraries/MySensors/core/MyLeds.cpp
libraries/MySensors/core/MyOTAFirmwareUpdate.cpp
libraries/MySensors/examples/BinarySwitchSensorIndication/BinarySwitchSensorIndication.ino
libraries/MySensors/examples/GatewayW5100/GatewayW5100.ino
libraries/MySensors/examples/GatewayW5100MQTTClient/GatewayW5100MQTTClient.ino

- Fix wrong definitions introduced in #462
- Fix compiler warnings
- Fix redefs related to SAMD

Fix MyIndication definitions

---

libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h

Enhance wait(ms,cmd,msgtype) to indicate if expected msg/msgtype received

Add return value to wait()

---

libraries/MySensors/MyConfig.h
libraries/MySensors/library.json

Corrected LED macro names in MyConfig.h, and updated library.json file with correct version number
(Pure cosmetic changes, won't break any builds..)

Small cleanups

---

libraries/MySensors/core/MySigning.cpp
libraries/MySensors/core/MySigning.h
libraries/MySensors/examples/SecurityPersonalizer/SecurityPersonalizer.ino

Also added debug prints for RF failures.

Signing troubleshooting guide in Doxygen

---

libraries/MySensors/core/MyHwESP8266.h
libraries/MySensors/core/MyMainESP8266.cpp

- updates to MyMainESP8266.cpp
- hwReboot: use ESP.restart() instead of wdt timeout

Update MyMainESP8266 to compile with ESPlib 2.3.0

---

libraries/MySensors/core/MyTransport.cpp
libraries/MySensors/core/MyTransport.h

- If radio init fails, transport SM is set to failure state until timeout

Improve radio fail state check

---

libraries/MySensors/core/MySigning.cpp

Add I_PING / I_PONG and I_REGISTRATION_REQUEST to exception list in MySigning.cpp

Add new internal commands to signing exception list

---

libraries/MySensors/core/MySensorsCore.cpp

- If no radio is defined, compiling MyTransport throws an error in sendHeartbeat()
- Adjustments to jenkins to test no-radio setups will follow

Fix MyTransport error

---

libraries/MySensors/drivers/ATSHA204/ATSHA204.cpp
libraries/MySensors/drivers/ATSHA204/ATSHA204.h

Also cleaned up trailing whitespaces in atsha204 core driver

Added return value for atsha204_getSerialNumber

---

core/MySensorsCore.cpp
core/MyTransport.cpp
core/MyTransport.h

- Fix issue with static parent assignment, this fixes #509 
- Fix GW callback
- Various minor code optimizations
- Update and unify transport log messages
- Doxygenize log messages

Updates to MyTransport

---

MyConfig.h
core/MyTransport.cpp
core/MyTransport.h
drivers/RF24/RF24.cpp

- nRF24: Fix #527 
- Doxygen documentation: Add table describing transport debug log messages
- Fix typos

Fix compatibility issue with nRF clones, update documentation

---

keywords.txt

MySensor keyword obsolete

---

core/MySensorsCore.h

* Update docs to new behavior.
* Add info on how to set wait time in smartSleep.
* Fix incorrect docs regarding return value of smartSleep.

Update doxygen docs with new smartSleep behavior

---

core/MyGatewayTransport.cpp
core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportSerial.cpp
core/MyInclusionMode.cpp

Rational: _msg is used for incoming messages

Use _msgTmp to build messages

---

core/MySensorsCore.cpp
core/MySensorsCore.h

- Adding debug output if before() and/or setup() are called provides useful information for troubleshooting

Add debug output if before() and setup() called

---

examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino

Analog checks for battery detection circuitry added to selftest

Updated sketch with analog check

---

MyConfig.h
core/MyHwATMega328.cpp
core/MyHwESP8266.cpp
core/MyHwSAMD.cpp
core/MySensorsCore.cpp
core/MySensorsCore.h

- unified sleeping function _sleep(), including smartSleep
- prevent sleeping if transport is not ready (until timeout)
- add debug log messages

Redesign sleep() functions

---

core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportMQTTClient.cpp
core/MyGatewayTransportSerial.cpp

Added GW RX indication for MQTT and Serial gateway (PR #585).
Only send RX indication when valid message has been received.

Fix gateway RX indication

---

examples/RelayActuator/RelayActuator.ino

Change V_Light for V_Status as V_Light is deprecated as per
https://www.mysensors.org/download/serial_api_20
Change S_Light for S_Binary as S_Binary is more generic.

V_Light Deprecated

---

examples/GatewayESP8266/GatewayESP8266.ino

Fix proposed by @RB3rg  in #559

Fix include for case sensitive systems

---

core/MyOTAFirmwareUpdate.cpp
core/MySensorsCore.cpp
core/MySensorsCore.h
core/MySigning.cpp
core/MyTransport.cpp

build(): Remove obsolete parameter (sender)

---

core/MyTransportRFM69.cpp

RFM69: wrong payload length reported

Fix payload length return

---

core/MyTransport.cpp

Fix routing table dump

---

MySensors.h
core/MyGatewayTransport.cpp
core/MySensorsCore.cpp
core/MySensorsCore.h
core/MySigning.cpp
core/MyTransport.cpp
core/MyTransport.h

Code harmonization

---

core/MyHwATMega328.h

See: http://www.atmel.com/webdoc/AVRLibcReferenceManual/group__avr__eeprom_1gac5c2be42eb170be7a26fe8b7cce4bc4d.html

Fix HAL inconsistency

---

MySensors.h
core/MyHw.h
core/MyHwATMega328.cpp
core/MyHwESP8266.cpp
core/MyHwLinuxGeneric.h
core/MyHwRPi.cpp
core/MyHwRPi.h
core/MyHwSAMD.cpp
core/MyMainLinux.cpp
drivers/Linux/Arduino.h
drivers/Linux/EthernetServer.cpp
drivers/Linux/Print.h
drivers/Linux/SerialPort.cpp
drivers/Linux/SoftEeprom.cpp
drivers/Linux/SoftEeprom.h
drivers/RPi/SPI.cpp
drivers/RPi/SPI.h
drivers/RPi/Wire.cpp
drivers/RPi/Wire.h
drivers/RPi/rpi_util.cpp

Add MyHw file for RaspberryPi.
Fix compilation warnings in x86.
Fix some error messages.

RPi: Add support for I2C

---

core/MyMainLinux.cpp

This was suggested by the forum user NiklasO.

RPi: Update messages for key generation

---

core/MySigning.cpp

- Made delay waiting for GW to transmit signing preferences apply
also if signing is disabled since nodes always sends a signing
presentation, and GW always replies with it's own presentation.
This can cause message collition if the node at the same time
proceed with other presentation messages.
- Made the signing backend "consume" signing presentation messages
sent by GW when signing is disabled. These messages should not
be forwarded to the "user".

Make stability improvements in message signing

---

MyConfig.h
core/MyHwATMega328.cpp
core/MyHwATMega328.h
core/MyHwESP8266.cpp
core/MyHwESP8266.h
core/MyHwSAMD.cpp
core/MyHwSAMD.h

- one setting for serial output size (applies to debug and gateway serial output)

Harmonize definition ins core

---

core/MyLeds.cpp

reported here : https://forum.mysensors.org/topic/5245/leds-on-gw-or-nodes-aren-t-working-as-expected

Fixes LED prevTime bug reported in forum

---

core/MyHwSAMD.cpp

- Rebooting
- Vcc(io) reporting
- Frequency reporting (currently F_CPU)

Implement SAMD core functions

---

core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportMQTTClient.cpp
core/MyLeds.cpp
core/MyLeds.h
core/MySensorsCore.cpp
core/MySensorsCore.h
core/MyTransport.cpp

Ref:
* https://forum.mysensors.org/topic/5245/leds-on-gw-and-nodes-aren-t-working-as-expected
* #636

Fix consistent yield usage & LED updates

---

core/MyOTAFirmwareUpdate.cpp
core/MyOTAFirmwareUpdate.h
core/MySensorsCore.cpp

- Harmonize code and rename structures
- Flash idle check before rebooting, see #647 
(PR tested with Sensebender V1 OTA FW update)

Harmonize OTA code, reboot when flash is idle

---

drivers/RFM95/RFM95.cpp
drivers/RFM95/RFM95.h

RFM95 updates for RPI

---

README.md
core/Version.h
library.json
library.properties

In preparation of the upcoming release:
- MySensors 2.1.0 (this includes all changes, bug fixes and improvements since 2.0.0 release)
- release date XMAS / 24.12.2016

Bump version to 2.1.0

---

core/MyTransport.cpp

- Prevent circular routing table update for BC messages

Refine routing table update

---

.gitignore
projects/SublimeText/MySensors.sublime-project

Various plugins exist to enhance the experience. The project
file contain references for all plugins it holds configurations
for.

Add a SublimeText 3 MySensors project

---

configure
core/MyHwRPi.h
drivers/RPi/cpuinfo.c
drivers/RPi/cpuinfo.h
drivers/RPi/rpi_util.cpp
drivers/RPi/rpi_util.h

Revision detection is done at runtime, the configure script has been
simplified to reflect this.

RPi: Improve board revision detection

---

core/MySensorsCore.cpp
core/MySensorsCore.h
tests/Arduino/sketches/serial_gateway_no_transport_full_debug/serial_gateway_no_transport_full_debug.ino

See here: https://forum.mysensors.org/topic/5466/serial-gateway-not-compiling-without-radio-support/2

Fix debug message

---

drivers/Linux/SoftEeprom.cpp
drivers/Linux/SoftEeprom.h
drivers/RPi/rpi_util.cpp

RPi: Use logError when possible

---

MySensors.h
core/MyGatewayTransport.cpp
core/MyGatewayTransport.h
core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportMQTTClient.cpp
core/MyGatewayTransportSerial.cpp
core/MyHwATMega328.h
core/MyHwESP8266.h
core/MyHwLinuxGeneric.h
core/MyHwSAMD.h
core/MySensorsCore.cpp
drivers/AVR/DigitalWriteFast/digitalWriteFast.h
drivers/RF24/RF24.cpp
drivers/RF24/RF24.h
examples/SoilMoistSensor/SoilMoistSensor.ino

- Fixes #707 
- Addresses #705 and #706 
- Fix Cppcheck errors

Minor optimizations & code harmonization

---

core/MyTransportRFM95.cpp
drivers/RFM95/RFM95.cpp
drivers/RFM95/RFM95.h
drivers/RFM95/RFM95registers.h

Update RFM95 driver

---

core/MySensorsCore.cpp
examples/MockMySensors/MockMySensors.ino

Fix getControllerConfig()

---

MySensors.h
core/MyHwAVR.cpp
core/MyHwAVR.h

several AVR archs can be used besides m328

Rename MyHwATmega328 to MyHwAVR

---

examples/PingPongSensor/PingPongSensor.ino
library.json

Consolidate open PRs for bugfix release

---

README.md
core/Version.h
library.json
library.properties

Reverts mysensors/MySensors#713
Required to sync branches in preparation of 2.1.1 release

Revert "Bump version to 2.2.0-beta"

---

examples/MockMySensors/MockMySensors.ino

Allows to run this sketch on an AVR 328 with
all sensors enabled.
Changes:
- use F() macro
- use msg_generic instead of individual variables

Reduce memory footprint

---

examples/MockMySensors/MockMySensors.ino

Reverts mysensors/MySensors #762:
@FotoFieber, please adjust your PR, see here for details:
https://ci.mysensors.org/job/Builders/job/ArduinoIDEBuilder/15973/consoleFull#183510198988e088db-13de-4c4f-bf4f-57e4627792d1
Essentially, the sketch is too big.

Revert "Reduce memory footprint"

---

MySensors.h
core/MyHwSAMD.cpp
core/MyHwSAMD.h
drivers/extEEPROM/LICENSE.md
drivers/extEEPROM/ReadMe.md
drivers/extEEPROM/examples/eepromTest/eepromTest.ino
drivers/extEEPROM/extEEPROM.cpp
drivers/extEEPROM/extEEPROM.h
drivers/extEEPROM/keywords.txt
drivers/extEEPROM/library.properties
examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino

fixes #784: Implement extEEPROM library for SAMD

I2C eeprom write fix for SAMD

---

configure

#756
- Documentation improvements.
- Fix bash warning.

Linux: Configure script update

---

core/MyHwAVR.cpp

AVR sleep with external interrupts fixes

---

configure
drivers/Linux/interrupt.cpp

Linux: Fix interrupt handler

---

examples_linux/mysgw.cpp

Linux: Add inclusion mode to gateway example

---

drivers/RFM95/RFM95.cpp

Linux: Fix compilation error for rfm95

---

MySensors.h
drivers/extEEPROM/extEEPROM.h
hal/architecture/MyHwTeensy3.cpp
hal/architecture/MyHwTeensy3.h
hal/architecture/MyMainTeensy3.cpp

Adding support for Teensy3.x boards
(Follow-up of #791)

Support for Teensy3.x boards

---

drivers/RFM69/new/RFM69_new.cpp

Fix RFM69 driver bug introduced in #848

Fix RFM69 driver

---

drivers/extEEPROM/extEEPROM.cpp

Fix: EEPROM::update()
- infinite loop when nBytes > 255

Fix ext. EEPROM update()

---

core/MyTransport.cpp

Fix for https://github.com/mysensors/MySensors/issues/867

Fix NRF5 radio encryption

---

core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportMQTTClient.cpp
examples/GatewayESP8266/GatewayESP8266.ino
examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino
examples/GatewayESP8266OTA/GatewayESP8266OTA.ino
examples/GatewayW5100/GatewayW5100.ino
examples/GatewayW5100MQTTClient/GatewayW5100MQTTClient.ino

- Fix UDP send
- Add a default value for MY_IP_GATEWAY_ADDRESS and
MY_IP_SUBNET_ADDRESS, making them optional when using MY_IP_ADDRESS
- Add support for MY_IP_GATEWAY_ADDRESS and MY_IP_SUBNET_ADDRESS to
W5100

Fix UDP on Ethernet gateway

---

MySensors.h
core/MySigning.cpp
core/MySigning.h
core/MySigningAtsha204Soft.cpp

* Data is not validated on Linux systems
* If encryption is enabled, data is also validated even if signing
is disabled.

Rewrite security personalization data validation

---

examples/AirQualitySensor/AirQualitySensor.ino
examples/BatteryPoweredSensor/BatteryPoweredSensor.ino
examples/BinarySwitchSleepSensor/BinarySwitchSleepSensor.ino
examples/CO2Sensor/CO2Sensor.ino
examples/DimmableLEDActuator/DimmableLEDActuator.ino
examples/DimmableLight/DimmableLight.ino
examples/DustSensor/DustSensor.ino
examples/DustSensorDSM/DustSensorDSM.ino
examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino
examples/GatewayESP8266/GatewayESP8266.ino
examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino
examples/GatewayESP8266OTA/GatewayESP8266OTA.ino
examples/GatewaySerial/GatewaySerial.ino
examples/GatewayW5100/GatewayW5100.ino
examples/GatewayW5100MQTTClient/GatewayW5100MQTTClient.ino
examples/LightSensor/LightSensor.ino
examples/MockMySensors/MockMySensors.ino
examples/MotionSensor/MotionSensor.ino
examples/PHSensor/PHSensor.ino
examples/PassiveNode/PassiveNode.ino
examples/PingPongSensor/PingPongSensor.ino
examples/RelayActuator/RelayActuator.ino
examples/RepeaterNode/RepeaterNode.ino
examples/SecretKnockSensor/SecretKnockSensor.ino
examples/SecureActuator/SecureActuator.ino
examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino
examples/SoilMoistSensor/SoilMoistSensor.ino
examples/UVSensor/UVSensor.ino
examples/VibrationSensor/VibrationSensor.ino
examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino

Added '#define MY_RADIO_NRF5_ESB' and '#define MY_RADIO_RFM95'
Fix: BinarySwitchSleepSensor pinMode

Update radio defines in examples

---

drivers/SPIFlash/SPIFlash.h

Added possibility to tune flash commands and parameters
in case off use non standard SPI flash for OTA

Added posibility to use non standard SPI Flash

---

hal/architecture/MyHwSTM32F1.h

Updates for latest STM32F1 board defs
- Jenkins: board defs updated to 2017.8.7

Update STM32 support

---

.mystools/cppcheck/options.sh
hal/architecture/MyHwNRF5.cpp
hal/architecture/MyHwNRF5.h

Sleep(0) results in no sleep without this fix.

NRF5: sleep() improvements

---

hal/architecture/MyHwNRF5.cpp

Fixes commit 5776d2b650573e76b155bd8c7bcb64f88ea5d11e
NRF5: Fix and improve sleep(0) (#909)

NRF5: Fix sleep()

---

core/Version.h

- alphanumerical (SemVer) and numerical library version representation

Add numerical library versioning

---

hal/architecture/MyHw.h
hal/architecture/MyHwAVR.cpp
hal/architecture/MyHwESP8266.cpp
hal/architecture/MyHwTeensy3.cpp

- add HW specific params for AVR (still, no unique ID)
- update padding bytes for ESP8266, Teensy

Update hwUniqueID() function

---

MyConfig.h
MySensors.h

Refactoring MyConfig.h resulted in continuously disabled sanity check

Fix sanity check feature

---

MyConfig.h

Correct NRF24 PA levels docs

---

core/MyGatewayTransportEthernet.cpp
core/MyOTAFirmwareUpdate.cpp
core/MyProtocolMySensors.cpp
core/MySensorsCore.cpp
core/MySigning.cpp
core/MySigningAtsha204.cpp
core/MySigningAtsha204Soft.cpp
core/MyTransport.cpp
drivers/NRF5/Radio_ESB.cpp
drivers/RF24/RF24.cpp
drivers/RFM69/new/RFM69_new.cpp
drivers/RFM95/RFM95.cpp
hal/architecture/MyHwAVR.cpp
hal/architecture/MyHwESP8266.cpp
hal/architecture/MyHwNRF5.cpp
hal/architecture/MyHwSAMD.cpp
hal/architecture/MyHwSTM32F1.cpp
hal/architecture/MyHwTeensy3.cpp

- Use portable debug prints, based on inttypes.h
- fix compiler warning

Make debug prints portable

---

core/MySensorsCore.cpp

Disable splash screen on GW

---

examples/AirQualitySensor/AirQualitySensor.ino
examples/BatteryPoweredSensor/BatteryPoweredSensor.ino
examples/CO2Sensor/CO2Sensor.ino
examples/DustSensor/DustSensor.ino
examples/DustSensorDSM/DustSensorDSM.ino
examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino
examples/LightSensor/LightSensor.ino
examples/MockMySensors/MockMySensors.ino
examples/MotionSensor/MotionSensor.ino
examples/MotionSensorRS485/MotionSensorRS485.ino
examples/PHSensor/PHSensor.ino
examples/SecurityPersonalizer/SecurityPersonalizer.ino
examples/SoilMoistSensor/SoilMoistSensor.ino
examples/UVSensor/UVSensor.ino
examples/VibrationSensor/VibrationSensor.ino
examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino

ESP8266: Fix example compilation error

---

.ci/Jenkinsfile
.ci/Jenkinsfile-nightly
.ci/arduino.groovy
.ci/doxygen.groovy
.ci/gitler.groovy
.ci/gitler.sh
.ci/linux.groovy
.ci/pipeline.groovy
.ci/pr-toolbox.groovy
.ci/static_analysis.groovy
README.md
hal/architecture/MyHw.h

Jenkins has been updated with new jobs that scan and execute
Jenkisfiles. These Jenkinsfiles encapsulates all logic for building and
validating the commits in both pull requests and merged pull requests.
Filestructure is as follows:
-  .ci/Jenkinsfile - This is the main Jenkinsfile that handles normal
pull request builds as well as merged pull request
post-validation.
Any repository in the MySensors GitHub organization
can implement this file and Jenkins will pick up
and execute it automatically.
-  .ci/Jenkinsfile-nightly - This perform merged pull request
post-validation using the nightly builds of
the Arduino IDE to provide early compliancy
status of the MySensors library for
upcoming releases of the Arduino IDE
-  .ci/ - This folder contain all the auxiliary scripts executed by the …

Implement jenkins pipelines as code

---

core/MyOTAFirmwareUpdate.h
core/MySensorsCore.cpp
core/MySensorsCore.h
core/MyTransport.h

Update Debug message tables

---

MyConfig.h
MySensors.h
core/MyCapabilities.h
core/MySigning.h

Also fixed spelling error in the MySigning documentation.

Add documentation for MyCapabilities

---

examples/RelayActuator/RelayActuator.ino

Based on feedback from skywatch,
https://forum.mysensors.org/post/78896
We'll need to update the wiring instructions on
https://www.mysensors.org/build/relay as well.

Update RelayActuator example

---

.ci/arduino.groovy

Update board name MyNRF5Board -> MyBoardNRF5

---

drivers/RF24/RF24.cpp
drivers/RFM69/new/RFM69_new.cpp
drivers/RFM95/RFM95.cpp

https://forum.mysensors.org/topic/8836/raspberry-pi-stability-problem/14

Linux: Fix null ptr exception

---

MyConfig.h
core/MyInclusionMode.cpp

Thanks to @TokTias for this idea and a starting point for the code.
This PR replaces https://github.com/mysensors/MySensors/pull/1029

Add MY_INCLUSION_LED_PIN for indicating inclusion mode status

---

README.md

Note that this PR will temporarily break the build status badges for the master branch until the release is made. So it should be merged as "late" as possible.

Update README.md for upcoming release

---

hal/transport/MyTransportRFM69.cpp

RFM69: Fix compiler warning

---

core/MyMessage.cpp
core/MyMessage.h
examples/SecretKnockSensor/SecretKnockSensor.ino
examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino

This should replace the static documentation at
http://korturl.nu/stupid
I have enabled existing comments and added new comments where
necessary. Feedback on syntax and contents is welcome.

Doxygenize MyMessage / Message manipulation

---

core/MySensorsCore.cpp

Fix smartSleep()

---

hal/architecture/AVR/MyHwAVR.cpp
hal/architecture/AVR/MyHwAVR.h

- Fixes #1032 
- implement UniqueID for AT328PB

AVR: Harmonize code

---

.ci/doxygen.groovy
.ci/gitler.groovy
Documentation/doxygen.sh
Documentation/mainpage.dox

* Let Gitler produce a changelog for release builds
* Fix bug in publishing release documentation
* Fix bug in labeling release documentation

Various CI-pipeline fixes

---

MyConfig.h
drivers/RFM69/new/RFM69_new.cpp
drivers/RFM69/new/RFM69_new.h
drivers/RFM69/new/RFM69registers_new.h
hal/transport/RFM69/MyTransportRFM69.cpp

- use IRQ flags
- reduce RAM usage (-50 bytes)
- reduce flash usage (-200 bytes)
- minor speed improvement
- implement CSMA
- Fixes #1051, #824

RFM69: Updates and optimizations

---

drivers/RF24/RF24.cpp
drivers/RF24/RF24.h
drivers/RF24/RF24registers.h
drivers/RFM69/new/RFM69_new.cpp
drivers/RFM69/new/RFM69_new.h
drivers/RFM95/RFM95.cpp
drivers/RFM95/RFM95.h

- Fix wrong variable names
- use dedicated namespace for transports

Fix variable names, minor updates

---

drivers/RFM69/new/RFM69_new.cpp
drivers/RFM69/new/RFM69_new.h
drivers/RFM95/RFM95.cpp
drivers/RFM95/RFM95.h
hal/transport/RF24/MyTransportRF24.cpp
hal/transport/RFM69/MyTransportRFM69.cpp
hal/transport/RFM95/MyTransportRFM95.cpp

Transport code harmonization

---

core/MyOTALogging.cpp
examples/LogOTANode/LogOTANode.ino
hal/architecture/SAMD/MyHwSAMD.h

AVR: Fix OTA logging

---

drivers/Linux/EthernetClient.cpp
drivers/Linux/EthernetServer.cpp

- Fix a problem where mysgw stops working and consumes a lot of cpu.
- Fix bug with tcp sockets where socket descriptor wasn't being freed.

Linux: Fix stability problem with ethernet

---

configure
core/MySigning.h
drivers/Linux/SoftEeprom.cpp
drivers/Linux/config.c
drivers/Linux/config.h
hal/architecture/Linux/MyMainLinuxGeneric.cpp

- Signing (HMAC, serial) and encryption keys are set through the configuration file.
- SoftEeprom update.

Linux: Support keys in config file

---

drivers/RF24/RF24.cpp

RF24: Minor power optimization

---

examples/GatewayESP8266/GatewayESP8266.ino
examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino
examples/GatewayESP8266OTA/GatewayESP8266OTA.ino

This fixes
https://github.com/mysensors/MySensors/issues/1096
Thanks to RWoerz for reporting this discrepancy.

Remove faulty wiring instructions from ESP gateways

---

examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino

some word corrections and sketch information

Word corrections

---

core/MySensorsCore.cpp

- add transport sanity check to identify transport issues before entering the main loop

Add transport sanity check before entering loop()

---

.ci/butler.groovy
.ci/butler.sh
.ci/pipeline.groovy

As discussed in #1124, some titles might be seen as non inclusive. Better to not use titles, but still be friendly and courteous.
I haven't tested this, and I'm not sure if I can.

Remove use of titles by CI Butler

---

.ci/arduino.groovy
.ci/pipeline.groovy

Jenkins: Update CI scripts + Arduino IDE 1.8.5

---

.ci/pipeline.groovy

This enables GitHub to show all statuses planned for execution.

Pre-register PR build statuses on GitHub

---

README.md
core/Version.h
library.json
library.properties

Initial commit for 3.0.0 development

---

.ci/arduino.groovy
drivers/RF24/RF24.cpp
hal/architecture/ESP8266/MyMainESP8266.cpp

- Fixes #1167
- Jenkins board defs updated

ESP8266: Updates to support 2.4.2 board defs

---

core/MyTransport.cpp

Send discovery message after GW startup to update/refresh routing table.

GW: Send discovery message after startup

---

MyConfig.h
configure
drivers/RFM69/new/RFM69_new.h

RFM69 frequency band for India - 865MHz

---

core/MyGatewayTransport.cpp
core/MySensorsCore.cpp
core/MySensorsCore.h
core/MyTransport.cpp
core/MyTransport.h

- Add log message for receive() callback
- Rename _processInternalMessages() => _processInternalCoreMessage()

Improve transport function & debug messages

---

drivers/RF24/RF24.cpp

https://forum.mysensors.org/topic/9655/delay-after-tsf-tri-tsb/14

RF24: Add delay after power-up

---

core/MySensorsCore.cpp
core/MySensorsCore.h

Allow flash strings in present() to save RAM

---

core/MyTransport.cpp

Fix recursion introduced in #1191

Fix internal message forwarding

---

.ci/arduino.groovy

Arduino IDE 1.8.7
AVR board defs 1.6.23
NRF5 board defs 0.6.0

Jenkins:Update Arduino 1.8.7

---

core/MySplashScreen.cpp

Reverts mysensors/MySensors#1210

Revert #1210

---

core/MySensorsCore.cpp
core/MySensorsCore.h

- Display release version in MCO:BGN:INIT output
- I_VERSION implementation: return library version as int

Display release number

---

core/MyGatewayTransportMQTTClient.cpp

MQTT GW: Add INDICATION_GW_RX

---

.ci/arduino.groovy
hal/architecture/ESP32/MyMainESP32.cpp

Incorporate changes to:
- arduino-builder 1.8.9 (currently nightly)
- ESP32 core (1.0.1-rc2)

Update CI scripts and ESP32 main

---

core/MySigningAtsha204Soft.cpp

RPI: Fix compilation error

---

.gitignore
core/MyGatewayTransportMQTTClient.cpp

Refactor of MY_MQTT_SUBSCRIBE_TOPIC_PREFIX and "/+/+/+/+/+" to support dynamic declaration of MY_MQTT_SUBSCRIBE_TOPIC_PREFIX.
Fixes #789

MQTT GW: Subscribe topic concatenation refactored

---

MyConfig.h
core/MyGatewayTransport.h
core/MyGatewayTransportEthernet.cpp
core/MyGatewayTransportMQTTClient.cpp
core/Version.h

- Code cleanup
- reconnect ETH: ESP8266 / ESP32 / W5100 tested
- reconnect MQTT: ESP8266 / ESP32 / W5100 tested

Maintenance: ethernet and MQTT code

---

MyConfig.h

RFM69 listenmode is not implemented, remove references.
- Fixes #1156

Cleanup: Remove RFM69 listenmode references

---

core/MySensorsCore.cpp

- Fix GW transport bug introduced in #1279

Fix GW transport

---

configure

This should fix https://github.com/mysensors/MySensors/issues/1303

Append instead of overwrite CXXFLAGS

---

MyConfig.h

This should fix
https://github.com/mysensors/MySensors/issues/1128

Add info on STM32, nRF5 and SoftSPI

---

examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino

Add support for less than 1 blink per hour
Apply Arduino IDE auto-formatting (readability++)

Energy meter pulse sensor itslav

---

examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino

Reverts mysensors/MySensors#1306
Please wait until #1309 is merged

Revert "Energy meter pulse sensor itslav"

---

core/MyMessage.h

Bug introduced in #1309
Fixes #1318

Fix protocol header

---

hal/transport/RFM69/driver/new/RFM69_new.cpp
hal/transport/RFM95/driver/RFM95.cpp

- Fix regression intoduced in #1317

Fix inverted noACK flag

---

core/Version.h
examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino
examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino
hal/architecture/MyHwHAL.h
hal/transport/RF24/driver/RF24.cpp
hal/transport/RFM69/driver/new/RFM69_new.cpp
hal/transport/RFM69/driver/old/RFM69_old.cpp
hal/transport/RFM95/driver/RFM95.cpp

ESP32/ESP8266: place ISR in IRAM

---

core/MySigningAtsha204.cpp
core/MySigningAtsha204Soft.cpp
drivers/SPIFlash/SPIFlash.cpp

Includes #1328 and #1336
- Fixes #1326

Cumulative update

---

core/MyProtocol.cpp

Fix segmentation fault

---

.ci/arduino.groovy

Update:
AVR board defs 1.8.1
ESP32 1.0.4
ESP8266 2.5.2
SAMD 1.8.4
STM32F1xx: 2019.10.9

CI: Update Arduino boards

---

.ci/butler.sh

#1358 (and others) showed that the butler check messages can be made clearer.
Hopefully, this change makes it more clear when there are no problems.

Make it clear when checks pass

---

.mystools/README.md

Thanks to @ltigges and @mkaiser for noticing that the documentation
needed an update and providing input.
This fixes #1359

Update mystools/README.md for WSL

---

hal/architecture/ESP8266/MyMainESP8266.cpp

changes, see https://github.com/esp8266/Arduino/releases

ESP8266: Update to 2.6.1

---

Makefile
configure
hal/architecture/Linux/drivers/BCM/bcm2835.c
hal/architecture/Linux/drivers/BCM/bcm2835.h

Fixing CI-related issues of #1353 (Credits to @phil2fer)

RPI: Add support for RPI4

---

README.md
core/Version.h
library.json
library.properties

Getting ready for 2.3.2 release :)

Bumping version to 2.3.2-rc.1
