libraries/MySensors/MyGateway.cpp
libraries/MySensors/MySensor.cpp

If a repeater responds to his parent node, this can cause a loop between the two.
(I managed to sign for both CLAs now)

fix a possible parent repeater loop

---

libraries/MySensors/MySensor.cpp

I_CHILDREN + C: clears routing table, parentnode and distance, followed by findParent(). This command is useful to re-discover network topology in case of repositioned or offline nodes.

Bugfix & Clear routing table extendend

---

libraries/MySensors/MySensor.cpp

childNodeTable is a pointer, will always return 2

fix clear routing table data

---

libraries/MySensors/MyGateway.cpp
libraries/MySensors/MySensor.cpp

In a gateway, I_FIND_PARENT_RESPONSE messages was returning as true by
process(). With this commit it will return as false, is this the right
expected behavior?

Accept a new parent only when autoFindParent is 1

---

libraries/MySensors/MySensor.cpp

To keep routing decisions in one place, and avoid rewriting the same
code to add failedTransmissions count to process()

process() uses sendRoute() for routing decisions

---

libraries/MySensors/MySensor.cpp

Gateway now only indicate signing requirements for sensors that in turn have indicated signing requirements.

Bugfix for gateway signing requirements

---

libraries/MySensors/MySensor.cpp

To prevent from sending a node id request before receiving a parent node id.
The original idea was to change the line 98:
if (nc.nodeId == AUTO) {
to:
if ( (nc.nodeId == AUTO) && (isValidParent(nc.parentNodeId)) ) {
To save a few bits I thought of joining the two ifs and remove (nc.nodeId != _nodeId) because we are now using "eeprom_update_byte".
Or we still need it for the OTA bootloader ?
https://github.com/mysensors/Arduino/commit/2d214a1e58ba3208a6f901791e351451c5b6a949

check valid parentNodeId before requestNodeId

---

libraries/MySensors/examples/MysensorMicro/MysensorMicro.ino
libraries/SI7021/SI7021.cpp
libraries/SI7021/SI7021.h

Updated library for si7021, in order to use combined read of both humidity and temperature, from Si7021 in MySensorsMicro demo sketch. Should save some conversion time, and save some battery power.

Small update to MysensorMicro sketch

---

libraries/MySensors/MySensor.cpp
libraries/MySensors/MySensor.h

process() altered the message buffer pending signing when
called in sign() causing the wrong message to be sent to the
signing backend. This is resolved by copying the original
message before processing incoming messages to make sure
the original message is kept. After it is successfully signed,
it is copied back to its original location again.

Fixed bug that caused the wrong message to be signed

---

libraries/MySensors/MyConfig.h
libraries/MySensors/MySensor.cpp
libraries/MySensors/MySensor.h
libraries/MySensors/MySigningAtsha204.cpp
libraries/MySensors/MySigningAtsha204.h
libraries/MySensors/MySigningAtsha204Soft.cpp
libraries/MySensors/MySigningAtsha204Soft.h
libraries/MySensors/MySigningNone.cpp
libraries/MySensors/examples/EthernetGateway/GatewayUtil.h
libraries/MySensors/examples/SecureActuator/SecureActuator.ino
libraries/MySensors/examples/SerialGateway/GatewayUtil.h
libraries/MySensors/examples/Sha204Personalizer/Sha204Personalizer.ino
libraries/MySensors/utility/ATSHA204.cpp
libraries/MySensors/utility/ATSHA204.h
libraries/PinChangeInt/PinChangeInt.h

Highlights of the changes in this pull request:
* Whitening of nonces (strengthens the quality of the random values)
* ATSHA personalizer updated to further simplify copy+paste
* Backend memory footprint reduced
* BUGFIX: EEPROM storage of signing request table now corrected
* Signing can be turned of by removing MY_SIGNING_FEATURE definition in MyConfig.h
* PinChangeInt library patched to only support one pin (and not use new). Reduces program size significantly.

Bugfixes and whitelisting support in signing backends

---

libraries/MySensors/examples/UVSensor/UVSensor.ino

Because the UVI graph is almost lineair
This gives a more accurate overview
Also the UVI is send at least every 5 minutes, this is good for the controller to know the sensor is still 'alive'

Enhanced the UVSensor example with 1 decimal to the UVI index.

---

libraries/MySensors/MyConfig.h
libraries/MySensors/MySensor.cpp
libraries/MySensors/MySensor.h
libraries/MySensors/examples/EthernetGateway/EthernetGateway.ino
libraries/MySensors/examples/EthernetGateway/GatewayUtil.h
libraries/MySensors/examples/SerialGateway/GatewayUtil.h
libraries/MySensors/examples/SerialGateway/SerialGateway.ino

Hi.
As we discussed in PR #66 I added the possibility to blink LEDs into the base MySensor class. I tested it with simple temperature sensor based on Arduino Mini Pro and with Serial Gateway. I also modified the Ethernet Gateway. I left the MQTT gateway as is, since I don't have testing setup for MQTT and the Gateway is not using the common GatewayUtil.h as the other two gateways.
Next step... move the inclusion mode feature into the base class (most probably reintroduced MyGateway class) without the interrupts library. And then finally rebase the dynamic discovery ;)

Add LEDs blinking into base MySensor class without any library dependency

---

hardware/MySensors/avr/boards.txt
libraries/MySensors/examples/SensebenderMicro/SensebenderMicro.ino

Added a define (and code), to enable battery voltage measurement reporting, as a normal sensor value. This will enable people to log battery voltage over time.
Default is disabled for ths functionality.

Added battery reporting as a sensor value

---

libraries/MySensors/utility/SPIFlash.cpp

In some cases, SPIFlash driver hangs during initialization
because it reads data from the SPI backend. But if SPI backend
has not been initialized, this fails.

Make sure SPI backend is initialized in SPIFlash driver

---

libraries/MySensors/examples/LightLuxSensor/LightLuxSensor.ino

LIGHT_SENSOR_ANALOG_PIN is not used in the code.

Remove unnecessary define

---

libraries/DallasTemperature/DallasTemperature.cpp
libraries/DallasTemperature/DallasTemperature.h
libraries/DallasTemperature/README.md
libraries/DallasTemperature/change.txt
libraries/DallasTemperature/examples/Alarm/Alarm.pde
libraries/DallasTemperature/examples/AlarmHandler/AlarmHandler.pde
libraries/DallasTemperature/examples/Multiple/Multiple.pde
libraries/DallasTemperature/examples/Single/Single.pde
libraries/DallasTemperature/examples/Tester/Tester.pde
libraries/DallasTemperature/examples/WaitForConversion/WaitForConversion.pde
libraries/DallasTemperature/examples/WaitForConversion2/WaitForConversion2.pde
libraries/DallasTemperature/keywords.txt
libraries/DallasTemperature/library.json
libraries/MySensors/examples/DallasTemperatureSensor/DallasTemperatureSensor.ino
libraries/OneWire/OneWire.cpp
libraries/OneWire/OneWire.h
libraries/OneWire/examples/DS18x20_Temperature/DS18x20_Temperature.pde

Updated DallasTemperature and OneWire libraries for non-blocking `requestTemperatures()` call. This allows deep sleep or process incoming messages during temperature conversion (up to 750 ms).

Non-blocking Dallas sensors temperature conversion

---

libraries/MySensors/examples/PressureSensor/PressureSensor.ino

- reduced footprint by storing only the last few samples instead of all 180
- fixed wrong calculation: 65/1023 factor replaced with a conversion factor hPa to kPa
- fixed error when 180 minutes were reached: sketch started at 5 min instead of 6 triggering a wrong average calculation
Cleaned up code
- removed unused variable
- fixed unit Pa to hPa in serial print
- introduced constants and enum for better readability
Signed-off-by: windkh <karl-heinz.wind@web.de>
I agree to the CLA!

Refactored forecast algorithm

---

libraries/MySensors/MyGateway.cpp
libraries/MySensors/MyGateway.h

LED/inclusion pins will always be controlled, even when not configured
to use them.
This fix will ignore pins when a negative pin number is passed.

Allow disabling of LED/Inclusion pins

---

hardware/MySensors/avr/boards.txt
hardware/MySensors/avr/platform.txt

Updated platform.txt / boards.txt to reflect AVR platform target, and removed atmega1284 as GW target, since it is using atsamd21 instead.

arduino target updates

---

hardware/MySensors/avr/platform.txt

This commit enables the Arduino IDE to configure MySensor specific
boards with more verbose warnings just as official Arduino boards.
Jenkins, build this please.

Allow MySensor specific boards to be compiled with warnings enabled

---

libraries/MySensors/examples/MockMySensors/MockMySensors.ino

MockSensor wouldn't compile w/ the 1.5 API's so I updated it.  Not all the fake sensor types work - some still need edits to make them work w/ 1.5 but the basic ones do.
I agree to the CLA here: https://www.clahub.com/agreements/mysensors/Arduino

Updated mock sensor code to newer hardware and radio API.

---

libraries/MySensors/MyConfig.h
libraries/MySensors/MyHwATMega328.cpp
libraries/MySensors/MySensor.cpp

With current design we could not use Tx/Rx as IO pin. I have added new variable 'ENABLED_SERIAL'. Disable this if you want to use Tx/Rx as IO pin in atmega328p.

Use Tx/Rx pin as IO pin

---

libraries/MySensors/examples/Esp8266Gateway/Esp8266Gateway.ino
libraries/MySensors/examples/Esp8266Gateway/GatewayUtil.h

Occasionally watchdog would trip causing a reset when a client (dis)connected.
Added support fot multiple sessions (Currently 5 max. Each connection
costs RAM!)
Each session can send data to the gateway. Data from the gateway will be
broadcasted to all connected clients.
Added serial logging of client (dis)connections. Inspect serial terminal
in case of problems.

Hardened (dis)connections

---

libraries/MySensors/MySensor.cpp

to match the description in http://forum.mysensors.org/topic/1021/security-introducing-signing-support-to-mysensors :
> However, the difference is that the gateway will only require signed messages from nodes it knows in turn require signed messages.

Mixed signing 2

---

hardware/MySensors/avr/platform.txt

This allows the MySensors AVR boards (SenseBender) to be built with
upcoming versions of the Arduino IDE.

Added preprocessor definitions to MySensors AVR boards

---

libraries/MySensors/examples/MQTTClientGateway/MQTTClientGateway.ino
libraries/MySensors/examples/MQTTGateway/MQTTGateway.ino

This seem to be mandatory for newer Arduino IDE versions.

Forward declare all inline functions

---

libraries/HeatpumpIR/CarrierHeatpumpIR.cpp
libraries/HeatpumpIR/CarrierHeatpumpIR.h
libraries/HeatpumpIR/FujitsuHeatpumpIR.cpp
libraries/HeatpumpIR/FujitsuHeatpumpIR.h
libraries/HeatpumpIR/HeatpumpIR.cpp
libraries/HeatpumpIR/HeatpumpIR.h
libraries/HeatpumpIR/HisenseHeatpumpIR.cpp
libraries/HeatpumpIR/HisenseHeatpumpIR.h
libraries/HeatpumpIR/IRSender.cpp
libraries/HeatpumpIR/IRSender.h
libraries/HeatpumpIR/MideaHeatpumpIR.cpp
libraries/HeatpumpIR/MideaHeatpumpIR.h
libraries/HeatpumpIR/MitsubishiHeatpumpIR.cpp
libraries/HeatpumpIR/MitsubishiHeatpumpIR.h
libraries/HeatpumpIR/PanasonicCKPHeatpumpIR.cpp
libraries/HeatpumpIR/PanasonicCKPHeatpumpIR.h
libraries/HeatpumpIR/PanasonicHeatpumpIR.cpp
libraries/HeatpumpIR/PanasonicHeatpumpIR.h
libraries/HeatpumpIR/README.md
libraries/HeatpumpIR/SamsungHeatpumpIR.cpp
libraries/HeatpumpIR/SamsungHeatpumpIR.h
libraries/HeatpumpIR/examples/HisenseTest/HisenseTest.ino
libraries/HeatpumpIR/examples/MideaRelayControl/MideaRelayControl.ino
libraries/HeatpumpIR/examples/MySensorsNode/MySensorsNode.ino
libraries/HeatpumpIR/examples/PanasonicCKPTimer/PanasonicCKPTimer.ino
libraries/HeatpumpIR/examples/simple/simple.ino
libraries/MySensors/examples/HeatpumpIRController/HeatpumpIRController.ino

The previous version used the '__PROG_TYPES_COMPAT__' definition. Now the library natively supports the Arduino IDE 1.6-style PROGMEM.

HeatpumpIR library updated to Arduino IDE 1.6 PROGMEM definition

---

libraries/MySensors/MyConfig.h
libraries/MySensors/utility/RF24.cpp
libraries/MySensors/utility/RF24.h
libraries/MySensors/utility/RF24_config.h

Switched from printf_P to Serial.print to prevent all kinds of nasty
PROGMEM troubles.
Distinguish between 32- and 16-bit architectures when reading ptrs from
flash.
Ditched #defines MINIMAL & SERIAL_DEBUG.
Debugging code is now only included when DEBUG is defined.
If your target (e.g. ATTiny) cannot handle the extra code, then don't
enable DEBUG.
#defining DEBUG will now also output a register-dump on calling begin()
of NRF24 driver to aid in (connection) problems.

Fix printDetails() & debugging for ESP8266

---

libraries/MySensors/MyTransportNRF24.cpp
libraries/MySensors/MyTransportNRF24.h

In v1.4 it was possible to change channel and datarate in the begin-statement.
This was very handy because I have a test-system with different channel next to a productive system. I do not want to edit MyConfig.h every time I compile something for the test-system.

Channel and Datarate in MyTransportNRF24 constructor

---

libraries/MySensors/core/Version.h

New version: 1.6.0-beta for development of 1.6.0.
See http://semver.org

Changed library version to comply with Semantic Versioning

---

libraries/MySensors/core/MySigning.h
libraries/MySensors/core/MySigningAtsha204.cpp
libraries/MySensors/core/MySigningAtsha204Soft.cpp

Signing backend debugs are now controlled by the MY_DEBUG flag.
This also means that on serial gateways, signing related debug
messages are forwarded to the controller with the appropriate
MySensors header information.

Refactored signing backend debug prints

---

libraries/HeatpumpIR/CarrierHeatpumpIR.cpp
libraries/HeatpumpIR/FujitsuHeatpumpIR.cpp
libraries/HeatpumpIR/MideaHeatpumpIR.cpp
libraries/HeatpumpIR/MitsubishiHeatpumpIR.cpp
libraries/HeatpumpIR/PanasonicCKPHeatpumpIR.cpp
libraries/HeatpumpIR/PanasonicHeatpumpIR.cpp
libraries/HeatpumpIR/README.md
libraries/HeatpumpIR/SamsungHeatpumpIR.cpp
libraries/HeatpumpIR/SharpHeatpumpIR.cpp
libraries/HeatpumpIR/SharpHeatpumpIR.h
libraries/HeatpumpIR/examples/simple/simple.ino
libraries/HeatpumpIR/keywords.txt
libraries/MySensors/examples/HeatpumpIRController/HeatpumpIRController.ino

* Support Sharp/IVT
* Change the IR carrier frequency of all heatpumps to 38 kHz
* 'Samsungbyte' was accidentally changed to 'Samsunguint8_t' when replacing 'byte' with 'uint8_t'

HeatpumpIR: Support Sharp/IVT heatpumps

---

libraries/MySensors/core/MyMessage.h

Requested by rob@domoticz for handling request of internal device
values. This variable/command should not be used for any of the official
sketches among the examples when communicating with controller.

Add V_CUSTOM for controller/inter-node specific commands.

---

.gitignore
libraries/MySensors/core/MyPrivateConfig.h.sample

libraries/MySensors/core/MyPrivateConfig.h.sample contain an example for
how private configuration data can be organized.
Rename that file to MyPrivateConfig.h and place it in the same folder
as the sketch you want to build and include it in order to add private
settings that you for various reasons do not want to store in git:
Make sure to place this include before
All MyPrivateConfig.h files are ignored by git.

Added support for private configuration data

---

libraries/MySensors/core/MyMainESP8266.cpp

You need to update to the latest ESP board files 2.0.0 by using
Tools->Board->Boards-Manager. Select ESP8266 and press Update.

Fix compile error using ESP board 2.0.0

---

libraries/MySensors/MyConfig.h
libraries/MySensors/drivers/RFM69/RFM69.cpp

Add delay when initializing radio and do some yielding

Fix MY_RF69_IRQ_NUM pin setting for ESP8266

---

libraries/MySensors/core/MyHw.h
libraries/MySensors/core/MyHwATMega328.cpp
libraries/MySensors/core/MyHwESP8266.cpp
libraries/MySensors/core/MyHwSAMD.cpp
libraries/MySensors/core/MySensorCore.cpp
libraries/MySensors/core/MySensorCore.h

- Fixing smartSleep(): 
change order of actions: sleep()>heartbeat()>wait() / before: wait()>sleep()>sendHeartbeat() 
This allows for receiving and processing commands after sleeping (if supported by the controller)
- Harmonize sleep return values: -2 not possible (e.g. FW update ongoing, not implemented), -1 timer wake up, >=0 interrupt# wake up.

Fixing smartsleep, define return value for sleep()

---

libraries/MySensors/core/MySigning.cpp
libraries/MySensors/core/MySigning.h

- Marcos for _doSign bitfield addressing not working bitwise
- For the sake of simplicity: changed _doSign definition to uint8_t array and adjusted size and macros accordingly

fix addressing bug in _doSign bitfield

---

libraries/MySensors/drivers/RF24/RF24.cpp

Logical not (!) precedes bitwise and (&), thus wrong evaluation of the return term.

Fix wrong value returned in isAckPayloadAvailable()

---

libraries/MySensors/core/MyMessage.cpp

Buffer overflow has been reported reported https://github.com/mysensors/Arduino/issues/312
This fix will limit the max. precision to 8

Limiting max. precision in dtostrf()

---

libraries/MySensors/core/MyHwATMega328.cpp
libraries/MySensors/core/MyHwESP8266.cpp
libraries/MySensors/core/MyHwSAMD.cpp
libraries/MySensors/core/MySensorCore.h
libraries/MySensors/core/MySigningAtsha204.cpp
libraries/MySensors/core/MySigningAtsha204Soft.cpp

Internal messages send from gateway to controller should use sensor id 255

Internal messages use sensor id 255

---

libraries/MySensors/core/MyMessage.cpp

string null termination missing in MyMessage.set(char*)

Null termination issue, Fixes #322

---

hardware/MySensors/samd/variants/mysensors_gw/variant.h
libraries/MySensors/MySensor.h
libraries/MySensors/examples/GatewaySerial/GatewaySerial.ino
libraries/MySensors/examples/GatewayW5100/GatewayW5100.ino
libraries/MySensors/examples/GatewayW5100MQTTClient/GatewayW5100MQTTClient.ino

Use MY_HW_xx_LED_PIN, if it is defined in board specific files, AND if MY_DEFAULT_xx_LED_PIN is not defined.
Commented out MY_DEFAULT_xx_LED_PIN defines in gateway sketches
if MY_DEFAULT_XX_LED_PIN is defined, it also enables MY_LEDS_BLINKING_FEATURE
If MY_LED_BLINKING_FEATURE is enabled, but no MY_DEFAULT_xx_LED_PIN are defined, then it will undefine MY_LED_BLINKING_FEATURE, as it doesn't make sense to include it if no LED's are defined.

LED HW definitions in arduino HW files overridable

---

libraries/MySensors/core/Version.h
libraries/MySensors/library.properties

Considering the magnitude of the delta between master and
development branch currently, 2.0.0-beta apperas to be a
more realistic version than 1.6.0-beta.

Bumped version to 2.0.0-beta

---

libraries/MySensors/examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino

If no pullup is used, the reported usage will be too high because of the floating pin.
Since an S0-enabled meter acts like a switch, we need a resistor to keep the pin from floating.

Use the internal pullup to be able to hook up this sketch directly to S0 meters

---

libraries/MySensors/core/MySigning.cpp

The message sender was retrieved from the message buffer after
prepareSigningPresentation() was called. This function resets
the message buffer so that is not the proper way to do it. Now,
the message sender is extracted first in signerProcessInternal()
in order to avoid the value being overwritten later on.

Make sure signing presentation data is sent correctly

---

libraries/MySensors/core/MyMainDefault.cpp

For atmega32U4-boards USBDevice.init(); must not be called. This is only necessary for SAMD-boards.
With this patch the library works fine with an arduino micro board.

Compatibility with atmega32U4 (Arduino micro)

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp

This change solve the problem described  here:
http://forum.mysensors.org/topic/2112/n00b-ethernet-gw-without-nf24
The presentation must be resent when the client connects. Without this Domoticz catches only sensor data, and doesn't know about connected actuators.

Resend presentation if client connected

---

libraries/MySensors/drivers/RFM69/RFM69.cpp

Needed on ESP8266 to avoid WDT kicking in - see http://forum.mysensors.org/topic/2278/esp8266-gateway-and-sensor-node-not-talking-noobie/34

Add yield() in sendACK

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp

An incompatibility exists with the wifi SetNoDelay() code between esp8266/Arduino version 2.0.0 and 2.1.0. This patch solves the problem for MySensors ESP8266 gateway until the SDK is fixed.
See https://github.com/esp8266/Arduino/issues/1695 for details of the actual problem.
The symptom is a gateway that keeps restarting after connection to controller due to an exception.
The solution was found by @sle118 in Mar 2016

Fix exception in esp8266 gateway. 

---

libraries/MySensors/core/MyGatewayTransportEthernet.cpp

If MY_ESP8266_SSID is not defined, the WIFI part is managed by the user.
If MY_ESP8266_SSID is defined, wifi is managed by Mysensor libraries.

Allow User to manage ESP8266 Wifi if need

---

libraries/MySensors/examples/GatewaySerial/GatewaySerial.ino

On 8 MHz clock speed the actual 115200 bps rate is so much off that sending
data over serial is very unreliable.

Set the serial port speed of the Serial Gateway to 38400 on Arduino's  running on 8MHz oscillator

---

libraries/MySensors/core/MySigning.cpp
libraries/MySensors/core/MySigning.h
libraries/MySensors/core/MyTransport.cpp

In order to allow a node to send signed messages to another node
the signingPresentation function can be called to make a
node2node presentation of signing preferences.
It is up to the sketch developer to make sure updated signing
preferences are communicated accordingly.

Add destination parameter to signingPresentation

---

libraries/MySensors/core/MyGatewayTransportSerial.cpp

E.g. 
"1;2;1;0;2;1\n1;11;1;0;2;1\n1;1;1;0;2;0\n1;2;1;0;2;0\n"

Allow sending multiple commands in one serial transmission

---

libraries/MySensors/examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino
libraries/MySensors/examples/IrrigationController/IrrigationController.ino
libraries/MySensors/examples/LightningSensor/LightningSensor.ino
libraries/MySensors/examples/MotionSensor/MotionSensor.ino
libraries/MySensors/examples/MotionSensorRS485/MotionSensorRS485.ino
libraries/MySensors/examples/RainGauge/RainGauge.ino
libraries/MySensors/examples/VibrationSensor/VibrationSensor.ino
libraries/MySensors/examples/WaterMeterPulseSensor/WaterMeterPulseSensor.ino

The examples used hard-coded values or defines to convert digital
pin number to interrupt in calls to attachInterrupt and sleep.
This has confused several people, most recently in
https://forum.mysensors.org/topic/3880/gw-sleep-on-battery-powered-magnet-door-switch/
Let digitalPinToInterrupt handle this work instead.
I agree to CLA.

Utilize digitalPinToInterrupt in examples

---

libraries/MySensors/core/MyMessage.h

Split #439  / Part 2
New C_INTERNAL msg types:
- I_PING/I_PONG: check connection to specified node and count hops
- I_REGISTER_REQUEST/I_REGISTER_RESPONSE: register node with GW
- I_DEBUG: remote debug (e.g. memory 'M', routing table 'R', frequency 'F', voltage 'V')

New msg types in preparation of transport rework

---

libraries/MySensors/core/MyMessage.h

New power metering variables introduced:
- V_VAR   Reactive power: volt-ampere reactive (var)
- V_VA   Apparent power: volt-ampere (VA)
- V_POWER_FACTOR   Ratio of real power to apparent power: floating point value in the range [-1,..,1]

Added power metering variables

---

libraries/MySensors/core/MySigningAtsha204.cpp
libraries/MySensors/core/MySigningAtsha204Soft.cpp
libraries/MySensors/drivers/ATSHA204/ATSHA204.cpp
libraries/MySensors/drivers/ATSHA204/ATSHA204.h
libraries/MySensors/tests/Arduino/sketches/hard_signing_no_whitelisting_full_debug/hard_signing_no_whitelisting_full_debug.ino
libraries/MySensors/tests/Arduino/sketches/hard_signing_whitelisting_full_debug/hard_signing_whitelisting_full_debug.ino
libraries/MySensors/tests/Arduino/sketches/hard_signing_whitelisting_full_debug_nodelock/hard_signing_whitelisting_full_debug_nodelock.ino
libraries/MySensors/tests/Arduino/sketches/hard_signing_whitelisting_full_debug_nrf24_rsa/hard_signing_whitelisting_full_debug_nrf24_rsa.ino
libraries/MySensors/tests/Arduino/sketches/hard_signing_whitelisting_full_debug_rfm69_rsa/hard_signing_whitelisting_full_debug_rfm69_rsa.ino
libraries/MySensors/tests/Arduino/sketches/soft_signing_no_whitelisting_full_debug/soft_signing_no_whitelisting_full_debug.ino
libraries/MySensors/tests/Arduino/sketches/soft_signing_whitelisting_full_debug/soft_signing_whitelisting_full_debug.ino

Various performance enhancements related to signing:
* Reduce codesize by purging c++ class usage in atsha driver
* Improve nonce quality by mixing it with a millisecond counter to get some more entropy
* Improve nonce calculation time in HW backend by only using one ATSHA-RNG value
* Enable ATSHA204 seed update when extracting random values
* Put ATSHA204 in idle mode instead of sleep mode during ongoing signing operations to improve response times.

Signing performance fixes

---

libraries/MySensors/core/MyTransport.cpp

Fix potential deadlock if parent not found for an extended amount of time

Fix reentry issue in stIDUpdate()

---

libraries/MySensors/core/MySensorsCore.cpp

- If radio is not initialized, wait() in gatewayTransportInit() (used to reconnect) will fail

Reshuffle gatewayTransportInit()

---

libraries/MySensors/core/MyTransport.cpp
libraries/MySensors/core/MyTransport.h

- Random delay to minimize collisions during findParent replies
- Set findParent threshold depending of node type
- Add failedUplinkTransmission counter to debug output (ft=%d)
- Remove redundant compiler directive

Minimize FindParent collisions and minor tweaks

---

libraries/MySensors/core/MyGatewayTransport.cpp
libraries/MySensors/core/MySensorsCore.cpp
libraries/MySensors/core/Version.h

not sure if the AltSoftSerial.h file will be affected, but I think I got everything else
```
grep -ir LIBRARY_VERSION *                                                     [13:04:26]
MySensors/core/Version.h:#define MYSENSORS_LIBRARY_VERSION "2.0.0-beta"
MySensors/core/MyGatewayTransport.cpp:                                  gatewayTransportSend(buildGw(_msg, I_VERSION).set(MYSENSORS_LIBRARY_VERSION));
MySensors/core/MySensorsCore.cpp:       debug(PSTR("Starting " MY_NODE_TYPE " (" MY_CAPABILITIES ", " MYSENSORS_LIBRARY_VERSION ")\n"));
MySensors/core/MySensorsCore.cpp:       _sendRoute(build(_msgTmp, _nc.nodeId, GATEWAY_ADDRESS, childSensorId, C_PRESENTATION, sensorType, enableAck).set(childSensorId==NODE_SENSOR_ID?MYSENSORS_LIBRARY_VERSION:description)); …
```

making MYSENSORS_LIBRARY_VERSION for purposes of being more unique

---

libraries/MySensors/core/MyTransport.cpp

If singing fails, transportSendWrite() stops processing a msg and returns false

Fix to prevent sending a msg if signing failed

---

core/MyHwATMega328.cpp

* Interrupts occurring during sleep-setup possibly fail to wake mcu
* Detach interrupt handler in interrupt handler to correctly handle
level-interrupts

Fix race in sleep with interrupts

---

core/MyHwATMega328.cpp

ATMega328 hardware abstraction used a mix of AVR cli/sei and Arduino
noInterrupts/interrupts calls.
Changed to use AVR cli/sei only.

Unify interrupt handling

---

core/MySensorsCore.cpp

Node needs to be registered before it can send sensor-related data (this excludes internal messages and routing). Calling _nodeRegistration() before setup() allows sending data in sketch setup().
- fixes #514

Call _nodeRegistration() before setup()

---

core/MyGatewayTransportEthernet.cpp

Calling WiFi.config() before WiFi.begin() forces begin() to configure the WiFi shield with the network addresses specified in config().
- Fixes #516

Calling WiFi.config() before WiFi.begin()

---

MySensors.h
core/MySensorsCore.cpp
core/MySensorsCore.h

Introducing transparent debug log format **SYSTEM[:SUB SYSTEM]:MESSAGE** for easier troubleshooting.
Example: `MCO:REG:REQ`
system: `MCO `refers to `MySensorsCore`
sub system: `REG `refers to `_registerNode()`
message: `REQ` = registration request

Cleanup debug messages in MySensorsCore

---

core/MySensorsCore.cpp

This is a resubmission of this PR:
https://github.com/mysensors/MySensors/pull/465
Wait for heartbeat is now done before going to sleep, instead of after waking up.
I've pulled in @abmantis commit to give credit where it belongs. Then I've fixed a couple of typos. There seem to be some whitespace fixes in there too. Rebased off development.
Tested with serial gateway and a node with one interrupt activated during smartsleep.

Fix smartsleep

---

core/MyMessage.cpp
core/MyMessage.h

MyMessage() should initialize all fields, otherwise MyMessages() created on stack will not have all members initialized correctly.

Correctly initialize MyMessage

---

MySensors.h

Emit error if MY_PARENT_NODE_IS_STATIC defined but MY_PARENT_NODE_ID is AUTO

Verify MY_PARENT_NODE_ID if parent is set static

---

core/MyMessage.h
core/MySensorsCore.cpp
core/MySigning.cpp
core/MyTransport.cpp

Rename internal messages to adhere to _request/_response naming scheme (if functionality not affected):
- I_DISCOVER -> I_DISCOVER_REQUEST
- I_HEARTBEAT -> I_HEARTBEAT_REQUEST
- I_FIND_PARENT -> I_FIND_PARENT_REQUEST

Harmonize message type names

---

drivers/RF24/RF24.cpp
drivers/RF24/RF24.h

- RF24_isDataAvailable(): returns true if RX FIFO not empty
- use _W_TX_PAYLOAD_NO_ACK_ for BC messages
- add RF24_getObserveTX()
- minor cosmetic changes

Updates to RF24 driver

---

core/MyHwATMega328.cpp

Fix issue #598
Pin interrupts used as wakeup source for hwSleep now get detached
correctly, also when the interrupts did not occur.

Fix detach pin interrupt in hwSleep

---

MySensors.h
core/MyGatewayTransportEthernet.cpp
core/MyHwATMega328.h
core/MyHwESP8266.h
core/MyHwLinuxGeneric.h
core/MyHwSAMD.h
core/MyInclusionMode.cpp
core/MyTransportRS485.cpp
drivers/AVR/DigitalWriteFast/digitalWriteFast.h
drivers/AltSoftSerial/AltSoftSerial.cpp
drivers/RF24/RF24.cpp
drivers/RFM69/RFM69.cpp
drivers/SPIFlash/SPIFlash.cpp
examples/GatewayW5100/GatewayW5100.ino

- Pin IO abstraction for all architectures
- use digitalWriteFast(), digitalReadFast() & pinModeFast() for AVR: speeding up pin access & reduce flash

HAL for digitalRead/Write() and pinMode()

---

drivers/RF24/RF24.cpp

https://forum.mysensors.org/topic/4803/building-a-raspberry-pi-gateway/103

Fix missing RF24_NOP refactoring

---

.gitignore
Makefile
configure
core/MyHwLinuxGeneric.cpp
core/MyHwLinuxGeneric.h
core/MyHwRPi.cpp
core/MyHwRPi.h
core/MyMainLinux.cpp
drivers/Linux/Arduino.h
drivers/RPi/rpi_util.cpp
drivers/RPi/rpi_util.h
examples_linux/mysgw.cpp
initscripts/mysgw.systemd
initscripts/mysgw.sysvinit

Add option to set an external arduino libraries directory. All libraries
from this folder will be compile and available for use in the gateway.
Some Arduino libraries can be used on Linux/RPI with none/minor adjustments,
but there are some that will have to be completely rewritten.
The build process uses a separate folder for objects and binary files
which can be set by the user.
Initialize the bcm2835 inside a class constructor to fix cases where pin
operations are used before hwInit().
Fix SPI pins default values.
Fix activation interrupt functions.
Fix some headers.
Rename gateway binary and services to mysgw.

RPi: Improve build process

---

hooks/install-hooks.sh
hooks/pre-commit.sh
tools/cppcheck/suppressions.cfg

It now supports both Linux and Windows and checks
both coding style (astyle) and does static code
analysis (cppcheck).
Tested using "Bash on Ubuntu on Windows" and the
git shell (via GitHub for Windows).
Installation for Linux users:
ln -s ../../hooks/pre-commit.sh .git/hooks/pre-commit
Installation for Windows users:
cp hooks/pre-commit.sh .git/hooks/pre-commit
Tools:
astyle (2.05.1 or newer)
cppcheck (1.76.1 or newer)

Update the pre-commit git hook

---

core/MyTransport.cpp
core/MyTransportNRF24.cpp

- decrypted messages are not processed due a payload length verification error.
- Fixes #677

Fix payload length verification

---

.mystools/.bundle_runtime.sh
.mystools/cppcheck/config/unix32.xml
.mystools/cppcheck/options.sh

* Using LIBRARY=avr|gnu git cppcheck ... will set the command
line library= to the value
* Corrected logical if error when bootstapping a pristine repo
References #672

Allow cppcheck library option override

---

core/MySensorsCore.cpp
core/MySensorsCore.h

Bug: GW-attached sensors cannot send messages if no radio-network defined.
- Fixes #697

Fix bug preventing GW-attached sensors to send messages

---

core/MyHwESP8266.cpp
core/MyHwESP8266.h

- use ESP8266 RNG in hwRandomNumberInit()
- _ADC_TOUT_ is set by default, _ADC_VCC_ if `MY_SPECIAL_DEBUG` enabled

ESP8266: Use RNG for randomSeed()

---

MyConfig.h
MySensors.h
core/MySensorsCore.cpp
core/MyTransport.cpp
core/MyTransport.h

- Use local functions: transportGetNodeId() and transportGetParentNodeId()
- Fix regression: _registerNode() call
- GW w/o radio: call presentation/registration functions upon init=ok
- Adjust debug log messages
- Adjust NWD / SAN / SRT timings

Use local ID functions, fix regression

---

drivers/ATSHA204/sha256.cpp

- Constructor/variable init. added due to Cppcheck result, this occupies 200 bytes of RAM even if class not used

Reduce memory footprint: -200 bytes

---

core/MyIndication.h
core/MyOTAFirmwareUpdate.cpp
core/MyOTAFirmwareUpdate.h
drivers/SPIFlash/SPIFlash.cpp
tests/Arduino/sketches/ota_firmware_update_nrf24/ota_firmware_update_nrf24.ino

This fixes the OTA FW block mismatch issue:
https://forum.mysensors.org/topic/5686/strange-behavior-of-rfm69-ota-burning-firmware-after-some-research
- add OTA test skript

OTA: Add incoming FW block check

---

core/MyHwAVR.h
drivers/AVR/DigitalWriteFast/digitalWriteFast.h

- Remove fast pin functions for several archs to reduce maintenance burden
- Fix ATmega168 compatibility
- Fixes #720 
- This supersedes PR #721

AVR: Restrict fast pin function use

---

core/MySigning.cpp

- Fix signing presentation bug (introduced in #690)
- skip signing of I_DISCOVER_REQUEST/RESPONSE messages

Fix signing presentation

---

MyConfig.h
core/MyIndication.cpp
core/MyIndication.h

- weak function definitions can cause a context-dependent null pointer execution. This has been observed for indication().
- To use own indication handler, define MY_INDICATION_HANDLER

Workaround for AVR-specific compiler issue

---

core/MyTransportRFM69.cpp

RF69_RESET / RF69_DIO5 was left unconfigured on the SenseBender Gateway, when using RFM69. This fixes it.

Added pin setup for RFM69 reset / dio5

---

core/MyGatewayTransportMQTTClient.cpp

ESP8266: Calling WiFi.config() before WiFi.begin() forces begin() to configure the WiFi shield with the network addresses specified in config().
See also #517

MQTT: Calling WiFi.config() before WiFi.begin()

---

core/MyHw.h
core/MyHwAVR.cpp
core/MyHwESP8266.cpp
core/MyHwLinuxGeneric.cpp
core/MyHwSAMD.cpp

- hwUniqueID() retrieves unique chip ID (if present)
- currently supported: SAMD, ESP8266

Add function to retrieve unique ID

---

MyConfig.h
MySensors.h
core/MyHwSTM32F1.cpp
core/MyHwSTM32F1.h
core/MyMainSTM32F1.cpp
drivers/RFM69/RFM69.cpp
drivers/RFM69/RFM69.h
library.properties

STM32F103 support, based on #727
- modification eeprom handling
- unique hwID
- rfm69 driver: select spi divider based on cpu freq
- tested rf24 and rfm69 radios

Add STM32F1 HW support

---

core/MyEepromAddresses.h
core/MyHw.h
core/MySensorsCore.cpp
core/MySigning.cpp
core/MySigning.h
core/MySigningAtsha204.cpp
core/MySigningAtsha204Soft.cpp
drivers/ATSHA204/ATSHA204.cpp
drivers/ATSHA204/ATSHA204.h
drivers/SPIFlash/SPIFlash.cpp
drivers/extEEPROM/extEEPROM.cpp
drivers/extEEPROM/extEEPROM.h
examples/SecurityPersonalizer/SecurityPersonalizer.ino
projects/SublimeText/MySensors.sublime-project

* Removed ability to lock data section
* Introduced "guided mode" to simplify process
* Refactored the sketch to be less monolithic
* Print details and instructions in tables
* Use device unique ID as serial when applicable
* Calculate and store personalization checksum

Security personalizer rewritten

---

core/MyHwAVR.cpp
core/MyHwAVR.h

Round requested sleep time up to next multiple of 16ms, to sleep at
least requested time.
Sleep time of 0 will return immediately.
Fixed watchdog sleep time calculation. AVR libc watchdog time
implementation is inconsistent, and requires larger flash/ram usage.

Fix watchdog sleep calculation

---

core/MyHwAVR.cpp

This is a small tweak to the last sleep fix. The last fix would clear the proper interrupt flag assuming interrupt1 is INT0 and interrupt2 is INT1. If interrupt1 is INT1 or interrupt2 is INT0, the sleep bug is still triggered.
e.g. `sleep(digitalPinToInterrupt(2), CHANGE, 0);` sleep bug is fixed
`sleep(digitalPinToInterrupt(3), CHANGE, 0)` still triggers the sleep bug
CC: @Yveaux

Sleep tweak: clear interrupt flag based on the interrupt used.

---

core/MyHwAVR.cpp

Support full AVR range, not only the ones supporting external interrupts 0 & 1.
Only tested on ATMega328 hardware however, as I have no other AVRs available ;-(

Fix clear pending ints for AVR

---

core/MyHwSTM32F1.cpp

I experienced some issues trying to use Serial1 on a STM32F103C8. This PR should address these:
- use MY_SERIALDEVICE in hwInit
- disable use of MY_SERIALDEVICE.flush() since the current STM32duino implementation performs a reset instead of an actual flush:

Corrections for stm32f1 serial communication

---

drivers/Linux/EthernetClient.cpp
drivers/Linux/EthernetClient.h
drivers/Linux/EthernetServer.cpp
drivers/Linux/EthernetServer.h

- Fix documentation.
- Add function close() to EthernetClient.
- Function connected() now return true if the connection is in
stablished state or there is still unread data.
- Update hasClient() to check if any client has disconnected.
- Fix _accept() to better handle the case of maximum clients reached.
- Fix peek() to return the next byte of the read queue.
- Simplifies write() of the server class.
- Implements flush().
- Updates read() to non-blocking type, the same way as in Arduino.

Linux: Fix Ethernet client and server

---

MySensors.h

UDP isn't implemented in Linux.

Linux: Give an error if UDP is selected

---

core/MySigningAtsha204Soft.cpp
examples/SecurityPersonalizer/SecurityPersonalizer.ino
hal/architecture/MyHw.h
hal/architecture/MyHwAVR.cpp
hal/architecture/MyHwAVR.h
hal/architecture/MyHwESP8266.cpp
hal/architecture/MyHwESP8266.h
hal/architecture/MyHwLinuxGeneric.cpp
hal/architecture/MyHwLinuxGeneric.h
hal/architecture/MyHwNRF5.cpp
hal/architecture/MyHwNRF5.h

This commit changes the way random numbers are available with MySensors. It's allowed to use a fast way for random number generation, which speeds up signing and allows longer battery life time.
On my hardware, without this patch, the AVR random generator is initialized with a value around ~240-200. With this patch, the AVR platform uses a 32 Bit random seed build from a floating
analog pin. The way of the generation of this seed is FIPS 140-2 compliant on my hardware. This reduces the risk generating the same nonce twice by switching the entropy from 6 bits to 32 bits and by a different runtime of hwRandomNumberInit().
For support MCU with a fast way to generate random data, the hwGetentropy() command is now available to allow rapid generation of random data.
The ESP8266 platform uses …

Enhance randomness (AVR, ESP8266, Linux, NRF5)

---

hal/architecture/MyHwLinuxGeneric.cpp

Now its compatible to Linux distributions without "linux/random.h". Fixes https://github.com/mysensors/MySensors/issues/854

Fix rasperry pi hwGetentropy()

---

hal/architecture/MyHwLinuxGeneric.cpp

Fix #860.
Makes hwRandomNumberInit() independent of hwInit().

Linux: Fix hwRandomNumberInit()

---

core/MySigning.cpp
core/MySigningAtsha204Soft.cpp

For soft signing, let backend handle checksum verification of
personalization data. This ensures that the backends sha256 library is
used and avoids an unnecessary instanitation of the public library.
For atsha204 signing, no checksum verification is made, just chip
locking flags.
Fixes #872

Let signing backend validate personalization

---

core/MySigning.cpp
core/MySigningAtsha204Soft.cpp
drivers/ATSHA204/sha256.cpp
drivers/ATSHA204/sha256.h

Hi,
due to memory constraints in some of my node sketches I looked for what's actually using a lot of memory and found some of the bits in the signing code to use some quite "big" chunks. Well... "big" in relation to the 2k total an Arduino has.
While my current need is addressed by #872 and #873, Patrick suggested that upcoming changes might reintroduce the extra memory consumption.
So, I looked for further chances to reduce the memory usage with the public signing API being used.
The individual Ideas each have their own commit... and most notably the last commit likely isn't acceptable.
This works for me (tm)... but I might be missing bits...
Please comment if there is anything I shall change/cleanup/... or if none of the ideas are acceptable ;)
Rainer

memory optimizations in signing

---

core/MyMessage.cpp
core/MyMessage.h
core/MySensorsCore.cpp
core/MySensorsCore.h

added variant of MyMessage::set and sendSketchInfo that accept a string that's stored in PROGMEM.
This avoids the need to (temporarily) store strings in memory to get them into a message and thereby saves memory.
I'm also using this to send literal error messages.
I haven't found any real cases in the MySensors tree that are using the __FlashStringHelper. If a variant similar to other progmem related functions using set_P(...) and sendSketchinfo_P(...) is preferred, please let me know.

Add progmem support for String messages

---

drivers/Linux/Arduino.h
drivers/Linux/Stream.cpp
drivers/PubSubClient/PubSubClient.cpp
drivers/PubSubClient/PubSubClient.h
drivers/SPIFlash/SPIFlash.cpp
drivers/SPIFlash/SPIFlash.h
drivers/pubsubclient/CHANGES.txt

In the Arduino IDE, boolean is an alias for bool.
The Arduino IDE might deprecate boolean in the future. See
https://github.com/arduino/Arduino/issues/4673 for details.
Command:
find drivers -type f | xargs sed -i 's/boolean/bool/g'

Use bool instead of boolean in drivers

---

hal/architecture/MyHwAVR.cpp
hal/architecture/MyHwESP8266.cpp
hal/architecture/MyHwNRF5.cpp
hal/architecture/MyHwSAMD.cpp
hal/architecture/MyHwSTM32F1.cpp
hal/architecture/MyHwTeensy3.cpp

Even with MY_DISABLED_SERIAL defined, the linker is still adding the Serial
object to the binary.
That's because a) the MySensors *.cpp files are actually included into
the sketch and compiled as part of it (and not compiled separately and
then linked) and b) due the the default(?) behavior of the linker
(https://github.com/arduino/Arduino/issues/4579).

Keep Serial from being linked when disabled

---

core/MySigning.cpp
drivers/ATSHA204/sha256.cpp
drivers/ATSHA204/sha256.h

Personalization does not need validation if the simple password
security flag is set.
Fixes #914

Skip check personalization with simple passwd flag

---

hal/architecture/MyHwNRF5.h

Without this commit, formatted outputs of 8 bit values dosn't work with arduino-nrf5 -> https://github.com/sandeepmistry/arduino-nRF5/issues/197

NRF5 fix 8 bit inttype handling

---

drivers/RF24/RF24.h

Ignores the RSSI value send back by NRF5 modules.

NRF24 disable DYN_ACK support

---

.ci/doxygen.groovy
configure

Use case: view the ./configure help text on the web.
This has been requested in
https://forum.mysensors.org/post/77751
Manually putting the help text in the forum or on mysensors.org
would lead to diverging documentation, no version management and
extra maintenance burden. This commit attempts to auto-generate
the documentation and use existing Doxygen infrastructure to
add the help text to the rest of the MySensors documentation.

Generate Doxygen from configure

---

.ci/static_analysis.groovy
.clang_complete
.mystools/cppcheck/config/suppressions.cfg
.mystools/cppcheck/options.sh
core/MyGatewayTransportEthernet.cpp
core/MyLeds.cpp
core/MyOTAFirmwareUpdate.cpp
core/MyProtocolMySensors.cpp
core/MySigning.cpp
core/MySigningAtsha204Soft.cpp
core/MyTransport.cpp
drivers/AES/AES.cpp
drivers/ATSHA204/sha256.cpp
drivers/AVR/DigitalIO/PinIO.h
drivers/AVR/DigitalIO/examples/SoftDS1307Utility/SoftDS1307Utility.ino
drivers/AltSoftSerial/AltSoftSerial.cpp
drivers/BCM/bcm2835.c
drivers/Linux/Stream.cpp
drivers/PubSubClient/PubSubClient.cpp
drivers/PubSubClient/PubSubClient.h
drivers/SPIFlash/SPIFlash.cpp
hal/transport/MyTransportRS485.cpp
projects/SublimeText/MySensors.sublime-project

* Add support for inline cppcheck suppressions
* Clean out all known cppcheck issues
* Terminate toll-gate on found cppcheck issues

CppCheck cleanup

---

drivers/NRF5/Flash.cpp
drivers/NVM/Flash.h
drivers/NVM/VirtualPage.cpp

This change takes care about the high flash memory used by the SoftDevice. The SoftDevice must be disabled via sd_softdevice_disable();

NVM: consideration of SoftDevice memory layout

---

drivers/RFM95/RFM95.cpp

RFM95 reset: pull reset pin low for 100uS, release, wait 5ms
see [datasheet](http://www.hoperf.com/upload/rf/RFM95_96_97_98W.pdf), chapter 7.2.2

Fix RFM95 reset

---

core/MyTransport.h

As discussed in
https://forum.mysensors.org/topic/7931/noob-cant-get-sensor-talking-to-gateway/
and numerous other forum threads, many people don't understand
that id generation is done by the controller.
Many new users start out their first MySensors network with a
gateway, a single sensor node and no controller. Since MySensors
defaults to AUTO node id, the node gets stuck on TSM:ID:FAIL,
like this:
TSM:ID
TSM:ID:REQ
TSF:MSG:SEND,255-255-0-0,s=255,c=3,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
TSM:ID
TSM:ID:REQ
TSF:MSG:SEND,255-255-0-0,s=255,c=3,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
TSM:ID
TSM:ID:REQ
TSF:MSG:SEND,255-255-0-0,s=255,c=3,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
TSM:ID
TSM:ID:REQ
TSF:MSG:SEND,255-255-0-0,s=255,c=3,t=3,pt=0,l=0,sg=0,ft=0,st=OK:
!TSM:ID:FAIL
This change adds a clarifying note about the …

Clarify TSM:ID:FAIL message

---

drivers/BCM/bcm2835.c

This makes it possible to compile the Raspberry Pi gateway on
Raspbian 9 (stretch), even without adding
--extra-cxxflags="-D__STDC_FORMAT_MACROS"
(as was suggested in
https://github.com/mysensors/MySensors/issues/955 but was
not related to this problem, Raspbian 7 still needs that define
after this change)
The compile problem was inadvertently introduced in
2d5404de9.
This change fixes the problem discussed in
https://github.com/mysensors/MySensors/issues/980
Working compilation after this fix:
```
pi@raspberrypi3:~/MySensors $ ./configure; make
[SECTION] Detecting target machine.
[OK] machine detected: SoC=BCM2837, Type=rpi3, CPU=armv7l.
[SECTION] Detecting SPI driver.
[OK] SPI driver detected:BCM.
[SECTION] Detecting init system.
[OK] init system detected: systemd.
[SECTION] Saving …
```

bcm driver: include inttypes

---

drivers/NRF5/Radio_ESB.cpp

Fix:
- If the buffer is full, a retransmit is ignored
- Remove superfluous stopping the timer

NRF5 ESB fix two states

---

CONTRIBUTING.md

As mentioned by per1234 in
https://github.com/mysensors/MySensors/pull/1008
we should make it easier to find the full code contribution
guidelines.
Since we have multiple git repos, we don't want to duplicate the
guidelines in each repo. Instead, we link to the canonical source
on mysensors.org.

Update reference to Code Contribution Guidelines

---

drivers/RFM69/new/RFM69_new.cpp
drivers/RFM69/new/RFM69_new.h

RFM69: Fix compiler warnings

---

drivers/Linux/SerialPort.cpp

This log message makes the Serial gateway print the serial port path,
similar to how the Ethernet gateway prints IP and port.
Example log output:
mysgw: Serial port /dev/MyCoolTTY (115200 baud) created

Linux/SerialPort: Log success message

---

Documentation/mainpage.dox
MyConfig.h

This saves 1kB of flash - enable only if needed (`#define MY_SIGNAL_REPORT_ENABLED`)

SignalReport disabled by default

---

.ci/gitler.sh

The guide we are referring to
( https://chris.beams.io/posts/git-commit/ )
says "shoot for 50 characters, but consider 72 the hard limit"
so let Gitler consider 72 the hard limit (instead of 50).

Relax Gitler on commit headline length

---

examples/SecretKnockSensor/SecretKnockSensor.ino
examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino

Fixes the following cppcheck issues:
examples/SecretKnockSensor/SecretKnockSensor.ino
305	variableScope	398	style
The scope of the variable 'timeDiff' can be reduced.
examples/SensebenderGatewaySerial/SensebenderGatewaySerial.ino
127	variableScope	398	style
The scope of the variable 'led_state' can be reduced.

Fix cppcheck issues

---

examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino

Added the define in the example sketch for MQTT GW, to make the option more accessible. 
(first commit)

Add URL option for mqtt broker in example sketch

---

MyConfig.h
configure
drivers/Linux/StdInOutStream.cpp
drivers/Linux/StdInOutStream.h
examples_linux/mysgw.cpp
hal/architecture/Linux/MyHwLinuxGeneric.cpp
hal/architecture/Linux/MyHwLinuxGeneric.h

- The symlink name for the PTY device is set using --my-serial-port
making --my-serial-pty deprecated
- Replace MY_LINUX_IS_SERIAL_PTY with MY_LINUX_SERIAL_IS_PTY
- MY_DEBUGDEVICE can be used to print debug messages from MySensors
(as it is currently in the other architectures)
- Rename SerialSimulator class to StdInOutStream
- Remove old deprecated option --my-radio

Linux: Serial minor update

---

MySensors.h
core/MySensorsCore.cpp
examples/SecurityPersonalizer/SecurityPersonalizer.ino

Fix MY_CORE_ONLY: Initialize HW

---

examples/GatewayESP8266/GatewayESP8266.ino
examples/GatewayESP8266MQTTClient/GatewayESP8266MQTTClient.ino

The comment for inclusion mode pin and the definition of
MY_INCLUSION_MODE_BUTTON_PIN did not match.
GPIO5 should be safe to use, while GPIO3 is used for the
UART which might result in conflict.
This fixes
https://github.com/mysensors/MySensors/issues/993

ESP8266 Gateway examples: clarify inclusion pin

---

.mystools/hooks/commit-msg.sh

The message hook validates that the c ommit message follows
the MySensors requirements.
More specifically, it checks that
- Commit message does not exceed a line length of 72 characters
- Commit title start with an uppercase character
- Commit title does not end with a period ('.')
Fixes #672

Add git commit message hook to the mystools bundle

---

drivers/RFM69/new/RFM69_new.h
drivers/RFM69/old/RFM69_old.h
drivers/RFM95/RFM95.h

This PR fixes #1075 by changing the default IRQ pin for RFM69 and RFM95 on ESP8266 to D1, which is in accordance to the [documentation](https://www.mysensors.org/build/connect_radio#rfm6995-&-esp8266).
I also changed the default for IRQ_NUM in the old RFM69 driver to get the interrupt number from the configured, not the default pin. This is intentionally done in a separate commit.
See also [forum thread](https://forum.mysensors.org/topic/9083/cannot-get-rfm69hw-connection-between-esp8266gw-and-pro-mini-sensor/26)

Fix default IRQ pins on ESP8266 that prevent MCU from boot

---

Documentation/doxygen.sh

No need to grep when we have a command that outputs
exactly what we want.

Simplify doxygen for ./configure

---

MyConfig.h
configure
drivers/Linux/SoftEeprom.cpp
drivers/Linux/SoftEeprom.h
drivers/Linux/config.c
drivers/Linux/config.h
drivers/Linux/log.c
drivers/Linux/log.h
examples_linux/mysgw.cpp
hal/architecture/Linux/MyHwLinuxGeneric.cpp
hal/architecture/Linux/MyHwLinuxGeneric.h
hal/architecture/Linux/MyMainLinuxGeneric.cpp
initscripts/mysgw.systemd
initscripts/mysgw.sysvinit

- The following settings can be use on the config file:
- verbose=[debug,info,notice,warn,err] - Logging verbosity. Default=debug
- log_file=[0|1] - Enable logging to a file. Default=0
- log_filepath=[/tmp/mysgw.log] - Log file path.
- log_pipe=[0|1] - Enable logging to a named pipe(aka fifo). Default=0
Use this option to view your gateway's log messages from the
log_pipe_file (defined below).
To do so, run the following command on another terminal:
- $ cat "log_pipe_file"
- log_pipe_file=[/tmp/mysgw.pipe]
- syslog=[0|1] - Enable logging to syslog. Default=0
- eeprom_file=[/etc/mysensors.eeprom]
- eeprom_size=[1024]
- Change some mysgw parameters:
- Added:
- -q, --quiet:  for quiet mode, disable log messages written to the
terminal.
- Removed:
- -d, --debug: removed, log messages are now …

Linux: Use config file for gateway settings

---

drivers/Linux/log.c

Use colored log messages only on the terminal.

Linux: Minor log fix

---

drivers/RF24/RF24.cpp

Linux: RF24 interrupt trigger workaround

---

MyConfig.h

Moved example values to the @ brief portion of Doxygen,
so the default (empty/undefined) values are visible
in Doxygen.

Clarify default defines

---

hal/architecture/AVR/MyHwAVR.cpp

For battery powered sensors which wake up by the RST Pin its useful to sleep the cpu forever. When using this command: sleep(INTERRUPT_NOT_DEFINED, MODE_NOT_DEFINED, 0, false); 
the code will be stripped down to hwSleep(0);. But this will not sleep the cpu forever.

Add sleep forever by sleep(0);

---

drivers/RFM69/new/RFM69_new.cpp
drivers/RFM95/RFM95.cpp

- Fixes a potential RFM69/95 deadlock if data instead of expected ACK is received
- RFM69: remove clearFIFO() redundancy

Fix RFMxx deadlock and minor optimization

---

examples/CO2Sensor/CO2Sensor.ino
examples/DustSensorDSM/DustSensorDSM.ino
examples/SoilMoistSensor/SoilMoistSensor.ino

A while ago, MySensors changed to use int32_t
instead of long int (and similar for other data
types). This change was not applied to all examples,
causing some examples to fail compilation for
ESP8266 with the following message:
call of overloaded 'set(long int)' is ambiguous
This update changes the casts to match the new style.
This fixes
https://github.com/mysensors/MySensors/issues/1129
Thanks to @henfri for reporting.

Update cast in msg.set

---

MySensors.h

This would let the user of the library know the platform they're using is not supported instead of throwing out hundreds of errors.

Add an error message about missing abstraction layer

---

.ci/static_analysis.groovy
.mystools/cppcheck/config/suppressions.cfg

- Details link on github for cppcheck now goes straight to the report
- Removed umatched suppression from the cppcheck suppression file

Refine cppcheck analysis

---

core/MyGatewayTransportEthernet.cpp

Code doesn't compile very well if statements are missing
a semicolon at the end.
This error snuck in in
https://github.com/mysensors/MySensors/pull/1110

Fix syntax error in MyGatewayTransportEthernet

---

drivers/RF24/RF24.cpp
drivers/RF24/RF24.h

Fix issue #1163. Prevent toggling advanced features on nRF24L01 non-plus versions.

Prevent toggle ACTIVATE

---

configure

Printing the CPPFLAGS might help people notice when they are
not including all parameters on one line.

Add CPPFLAGS to configure output

---

core/MyTransport.cpp
core/MyTransport.h
examples/Node2Node/Node2Node.ino

This enables direct node-to-node traffic (re-routing via parental node if direct communication fails)

Direct node2node traffic

---

drivers/RF24/RF24.cpp

see https://forum.mysensors.org/topic/9642/nrf24-transmission-of-data-works-fine-but-constant-nack-s-produced
Comment by @Yveaux:
"The CE pulse is apparently used by amplified nrf24 radios to enable the lna receiver. This is not an issue when only sending, but for hardware acks the lna receiver should be enabled until the transmitted message has been acknowledged by the receiving node.
Shortening the CE pulse, and thereby disabling reception causes nacks to occur..."

RF24: Fix RX issue regarding PA+LNA modules

---

drivers/RF24/RF24.cpp
drivers/RF24/RF24.h
drivers/RF24/RF24registers.h

For testing & diagnostics purposes only!
These functions are not used by the regular MySensors stack.

Add lowlevel nRF24 functions

---

MySensors.h
core/MySigningAtsha204Soft.cpp
hal/architecture/AVR/MyHwAVR.h
hal/crypto/AVR/MyCryptoAVR.h

- Fix: Stack corruption in AVR SHA256 ASM implementation due to non-static buffer definition

AVR: Fix variable scope in SHA256 ASM

---

core/MyInclusionMode.cpp

- Fixes #1196
According to arduino references we should instead use INPUT_PULLUP as of Arduino 1.0.1
https://www.arduino.cc/en/Tutorial/DigitalPins

Inclusion mode: change pinmode to INPUT_PULLUP

---

configure
drivers/BCM/BCM.cpp
drivers/BCM/BCM.h
drivers/BCM/SPIBCM.cpp
drivers/Linux/SPIDEV.cpp
drivers/Linux/SPIDEV.h
drivers/RF24/RF24.cpp
drivers/RFM69/new/RFM69_new.cpp
drivers/RFM95/RFM95.cpp

Fix SPIDEV on Armbian Stretch

---

core/MyGatewayTransportMQTTClient.cpp

Fix #788, causing crash on ESP8266 when Wifi connection to AP fails with MQTT connected.

Add MQTT Wifi connection status check

---

MySensors.h
hal/architecture/AVR/MyHwAVR.cpp
hal/architecture/AVR/MyHwAVR.h
hal/architecture/ESP32/MyHwESP32.h
hal/architecture/ESP8266/MyHwESP8266.h
hal/architecture/Linux/MyHwLinuxGeneric.h
hal/architecture/NRF5/MyHwNRF5.h
hal/architecture/SAMD/MyHwSAMD.h
hal/architecture/STM32F1/MyHwSTM32F1.h
hal/architecture/Teensy3/MyHwTeensy3.h
hal/transport/RF24/driver/RF24.h
hal/transport/RFM69/driver/new/RFM69_new.h
hal/transport/RFM69/driver/old/RFM69_old.cpp
hal/transport/RFM69/driver/old/RFM69_old.h
hal/transport/RFM95/driver/RFM95.h

Add hwSPI to HAL

---

hal/architecture/Linux/drivers/core/log.c

The log file was no flushed, which meant that the lines logged
would not be visible in the file until (much) later, often
not until the gateway process exited.
By flushing the file, log information becomes available immediately.

Rpi: flush log file

---

core/MySensorsCore.cpp

- Add heartbeat functionality for GW-only mode w/o defined transport network
see here: https://forum.mysensors.org/topic/10314/heartbeat-gateway

Enable heartbeat for GW-only mode

---

core/MySensorsCore.cpp
core/MySensorsCore.h
hal/architecture/AVR/MyHwAVR.cpp
hal/architecture/AVR/MyHwAVR.h
hal/architecture/ESP32/MyHwESP32.h
hal/architecture/ESP8266/MyHwESP8266.h
hal/architecture/Linux/MyHwLinuxGeneric.h
hal/architecture/NRF5/MyHwNRF5.h
hal/architecture/SAMD/MyHwSAMD.h
hal/architecture/STM32F1/MyHwSTM32F1.h
hal/architecture/Teensy3/MyHwTeensy3.h

Add support to retrieve remaining sleep time when wake up by interrupt.
Only implemented for AVR; other architectures except NRF5 don't sleep. Unsure if NRF5 can retrieve remaining sleep time.
As AVR sleeps using watchdog in 8192ms or smaller steps, the reported remainign time can be up to roughly 8 seconds off.

Added getSleepRemaining to core

---

MyConfig.h

https://www.mysensors.org/apidocs/group__RadioSettingGrpPub.html
had the headline "Radio selection". In MySensors lingo, we
probably mean "Transport selection", especially since RS485 is
included but does not use radio.
By renaming the group and the text, it might become easier for
users to understand which different transports are supported
by MySensors.
This fixes https://github.com/mysensors/MySensors/issues/1272

Rename RadioSettingGrpPub to TransportSettingGrpPub

---

MyConfig.h

This fixes
https://github.com/mysensors/MySensors/issues/1128

Document esp8266 limitation for MY_RX_MESSAGE_BUFFER_FEATURE

---

core/MyProtocol.cpp

Bug: Serial messages with empty payload field are discarded

Fix serial protocol parser

---

configure

Printing the CXXFLAGS might help people notice when they are
not including all parameters on one line.
Printing of CPPFLAGS was added in cd4acb2b8.

Add CXXFLAGS to configure output

---

examples/EnergyMeterPulseSensor/EnergyMeterPulseSensor.ino

Revert the revert 1306 energy meter pulse sensor itslav

---

hal/transport/RF24/driver/RF24.cpp
hal/transport/RF24/driver/RF24.h

- Fix status byte return
- Set ARC=0 for noACK messages
- Suppress debug output for RF24_isDataAvailable() polling
- Clear RX_DR IRQ flag (for ACKs with payload, currently unused)

RF24 improvements

---

core/MyTransport.cpp
hal/transport/RFM69/MyTransportRFM69.cpp
hal/transport/RFM69/driver/new/RFM69_new.cpp
hal/transport/RFM69/driver/new/RFM69_new.h
hal/transport/RFM95/MyTransportRFM95.cpp
hal/transport/RFM95/driver/RFM95.cpp
hal/transport/RFM95/driver/RFM95.h

- Handle noACK flags globally: BC messages & passive mode
- Follow up of #1316

Move noACK control to transportSendWrite()

---

library.json

.mystools causes the stupid warning "Spurious folder" in the Arduino IDE, confusing our users
projects (Sublime-specific files)
examples_linux (only applicable for the rpi gw)
initscripts  (only applicable for the rpi gw)
configure   (only applicable for the rpi gw)
.ci (files for Jenkins)
None of these files are useful in the Arduino IDE context (and probably not for PlatformIO either, which uses the same library file).
People who do have a use for these files will probably check out the code from github instead (or at least download the zip from github), resulting in a full download with all files.

Exclude items from the Arduino library package

---

core/MyMessage.cpp
core/MyMessage.h
core/MyTransport.cpp
hal/transport/MyTransportHAL.cpp
hal/transport/MyTransportHAL.h

- Adjust parameter names
- simplify setVersion()

MyMessage class maintenance

---

core/MyTransport.cpp
core/MyTransport.h
core/Version.h

- Fix: do not set nodeID to AUTO if invalid I_ID_RESPONSE received
- Save 2 bytes of RAM: remove transportSM variable (uplinkQualityRSSI) if unused
- Bump pre-release version to 7

MyTransport update

---

Logparser/logparser.js

Add message for ID:FAIL to log parser.
Before:
After:

Add id failed to logparser

---

hal/architecture/Linux/drivers/core/GPIO.cpp

Use snprintf instead of sprintf to avoid a potential buffer overflow, as noted by the compiler:
hal/architecture/Linux/drivers/core/GPIO.cpp: In constructor ‘GPIOClass::GPIOClass()’:
hal/architecture/Linux/drivers/core/GPIO.cpp:53:18: warning: ‘%s’ directive writing up to 255 bytes into a region of size 48 [-Wformat-overflow=]
sprintf(file, "/sys/class/gpio/%s/base", de->d_name);
^~~~~~~~~~~~~~~~~~~~~~~~~
hal/architecture/Linux/drivers/core/GPIO.cpp:53:11: note: ‘sprintf’ output between 22 and 277 bytes into a destination of size 64
sprintf(file, "/sys/class/gpio/%s/base", de->d_name);
~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
hal/architecture/Linux/drivers/core/GPIO.cpp:62:18: warning: ‘%s’ directive writing up to 255 bytes into a region of size 48 [-Wformat-overflow=] …

Fix potential buffer overflow

---

hal/architecture/Linux/drivers/core/SoftEeprom.cpp

_fileName and _values have to be re-set to NULL, otherwise a double-free might occur.
First destroy() is called when the eeprom filesize does not match, the second destroy() is called from the dtor of SoftEeprom on exit:
Nov 11 17:00:01 INFO  Starting gateway...
Nov 11 17:00:01 INFO  Protocol version - 2.3.2-beta
Nov 11 17:00:01 ERROR EEPROM file /etc/mysensors.eeprom is not the correct size of 1024.  Please remove the file and a new one will be created.
double free or corruption (!prev)
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x76c6ed2c in __GI_abort () …

Fix double free
